async page=>{
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');localStorage.removeItem('fasl-motion');});await page.reload();await page.setViewportSize({width:390,height:844});await page.locator('#explore').click();await page.locator('#dismiss-orientation').click();
await page.locator('[data-drawer=care]').click();await page.keyboard.press('Tab');ok(await page.evaluate(()=>document.activeElement.closest('#drawer')!==null),'Keyboard focus stays inside the modal');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement.matches('[data-drawer=care]'));ok(true,'Escape closes details and returns focus to its trigger');
await page.locator('#compare-straw').click();await page.locator('#change-residue').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement.id==='compare-straw');ok(true,'Optional straw dialog dismisses with a usable focus destination');
await page.locator('#play').focus();ok(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle==='solid'),'Keyboard focus has a visible outline');
const targets=await page.evaluate(()=>[...document.querySelectorAll('.primary,#play,[data-scene],#language-toggle,.menu,[data-view],[data-unit]')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));ok(targets.every(e=>e.w>=44&&e.h>=44),'Primary controls have 44 px touch targets '+JSON.stringify(targets));
// Measure the solid UI palette; this is not a whole-page WCAG conformance claim.
for(const mode of ['light','dark']){await page.evaluate(m=>document.documentElement.dataset.theme=m,mode);const ratio=await page.evaluate(()=>{const rgb=name=>getComputedStyle(document.documentElement).getPropertyValue(name).trim(),lum=hex=>{const a=hex.replace('#','').match(/.{2}/g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722;},a=lum(rgb('--muted')),b=lum(rgb('--surface'));return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);});ok(ratio>=4.5,mode+' muted body text has at least 4.5:1 contrast');}
await page.evaluate(()=>document.documentElement.dataset.theme='light');
await page.locator('#timeline-slider').fill('304');await page.waitForFunction(()=>document.querySelector('#story-finish').hidden===false);
await page.evaluate(()=>{for(const e of document.querySelectorAll('h1,h2,p,button,small,.eyebrow')){const size=parseFloat(getComputedStyle(e).fontSize);e.style.fontSize=size*1.5+'px';}});await page.waitForTimeout(150);
ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Enlarged text has no horizontal overflow');ok(await page.evaluate(()=>{const card=document.querySelector('#story-finish').getBoundingClientRect(),bowl=document.querySelector('#harvest-reveal').getBoundingClientRect();return card.bottom<bowl.top&&document.querySelector('#try-straw').getBoundingClientRect().bottom<=card.bottom;}),'Enlarged final text and actions stay inside the story card');await page.screenshot({path:'output/playwright/accessibility-large-text.png',fullPage:true});
const fallback=await page.context().newPage();try{await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:original.call(this,type,...args);};});await fallback.goto('http://127.0.0.1:8080/');await fallback.locator('#explore').click();await fallback.locator('#timeline-slider').fill('304');await fallback.waitForFunction(()=>document.querySelector('#story-finish').hidden===false);ok(await fallback.locator('.webgl-fallback').isVisible(),'WebGL failure has a meaningful text fallback');ok(await fallback.locator('#harvest-reveal').isVisible(),'Bowl and final results work without WebGL');await fallback.locator('#compare-crops').click();ok((await fallback.locator('#drawer-content').textContent()).includes('Pumped per 100 g'),'Quantitative results remain usable without WebGL');}finally{await fallback.close();}
ok(errors.length===0,'No JavaScript errors in access checks');return{passed:checks.length,checks};
}
