async page=>{
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m)};
await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');localStorage.setItem('fasl-units','bowl')});await page.reload();await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>window.Fieldnotes?.Scene3D.info().renderer);
const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,n)};
await seek(95);const before=await page.evaluate(()=>({target:Fieldnotes.getTimeline().target,state:JSON.stringify(Fieldnotes.getResult().state),builds:Fieldnotes.Scene3D.info().geometryBuilds}));
await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend>.98);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().visiblePlantClumps===48),'Acre view shows 48 representative clumps');ok(await page.evaluate(n=>Fieldnotes.getTimeline().target===n,before.target),'Zoom preserves time');ok(await page.evaluate(n=>JSON.stringify(Fieldnotes.getResult().state)===n,before.state),'Zoom preserves simulation');ok(await page.evaluate(n=>Fieldnotes.Scene3D.info().geometryBuilds===n,before.builds),'Switching units reuses crop geometry');
await page.screenshot({path:'output/playwright/acre-field-final.png'});
await seek(2);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().growth<.3),'Acre seedlings grow continuously');await seek(95);
for(const [width,height] of [[320,568],[390,667],[1440,1000]]){await page.setViewportSize({width,height});await page.waitForFunction(()=>document.querySelector('canvas').getBoundingClientRect().height===innerHeight);await page.screenshot({path:`output/playwright/acre-${width}-${height}.png`});ok(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.querySelector('#groundwater-marker').getBoundingClientRect().bottom<document.querySelector('footer').getBoundingClientRect().top),'Field and groundwater fit '+width+'×'+height);}
await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend<.02);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().visiblePlantClumps===1),'Bowl returns to single crop');
await page.locator('.menu').click();await page.locator('#motion').click();await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend===1);ok(true,'Reduced motion changes view immediately');await page.locator('[data-scene=wheat]').click();await page.locator('[data-residue=mulch]').click();await seek(250);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().crop==='wheat'&&Fieldnotes.Scene3D.info().visiblePlantClumps===48),'Wheat uses field rows');ok(errors.length===0,'No browser errors');return{passed:checks.length,checks,drawCalls:await page.evaluate(()=>Fieldnotes.Scene3D.info().drawCalls)};
}
