async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
 await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');localStorage.setItem('fasl-units','acre');localStorage.removeItem('fasl-motion');});await page.reload();await page.locator('#explore').click();await page.setViewportSize({width:390,height:844});
 const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Fieldnotes.getTimeline().position===n&&Fieldnotes.Scene3D.info().position===n,n);};
 await seek(95);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend>.98);const before=await page.evaluate(()=>({target:Fieldnotes.getTimeline().target,state:JSON.stringify(Fieldnotes.getResult().state),builds:Fieldnotes.Scene3D.info().geometryBuilds}));
 ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().visiblePlantClumps===96),'Field shows 96 varied clumps with detailed foreground plants');await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend<.02);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().visiblePlantClumps===1),'100 g presents a large representative plant');ok(await page.evaluate(s=>JSON.stringify(Fieldnotes.getResult().state)===s,before.state),'Presentation preserves the simulation');ok(await page.evaluate(n=>Fieldnotes.getTimeline().target===n,before.target),'Presentation preserves date');ok(await page.evaluate(n=>Fieldnotes.Scene3D.info().geometryBuilds===n,before.builds),'Quantity modes reuse crop geometry');
 await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend>.98);await seek(2);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().growth<.3),'Seedlings retain continuous growth');await seek(95);
 for(const [w,h] of [[320,568],[390,667],[1440,1000]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(150);ok(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.querySelector('canvas').getBoundingClientRect().height===document.querySelector('.field-scene').clientHeight),'Scene adapts to container size at '+w+'×'+h);}
 await page.locator('.menu').click();await page.locator('#motion').click();await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend===0);await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend===1);ok(true,'Reduced motion switches modes immediately');await page.locator('[data-scene=wheat]').click();await seek(250);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().crop==='wheat'&&Fieldnotes.Scene3D.info().visiblePlantClumps===96),'Wheat uses the varied field canopy');ok(errors.length===0,'No browser errors');return{passed:checks.length,checks};
}
