async page=>{
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');localStorage.removeItem('fasl-motion');});await page.reload();await page.locator('#explore').click();
const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Fieldnotes.getTimeline().position===n&&Fieldnotes.Scene3D.info().position===n,n);};
await page.locator('[data-scene=wheat]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().sample.id==='wheat');ok(!(await page.locator('#residue-dialog').isVisible()),'Wheat navigation does not require a management choice');await page.locator('#compare-straw').click();await page.locator('#change-residue').click();await page.locator('[data-residue=burn]').click();await seek(122);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fireVisible),'Burn path shows fire');await seek(160);ok(await page.evaluate(()=>!Fieldnotes.Scene3D.info().fireVisible&&Fieldnotes.Scene3D.info().residueVisible),'Fire ends while ash remains');
await page.locator('#soil-status').click();ok((await page.locator('#drawer-content').textContent()).includes('5.15'),'Soil details keep research observations separate');await page.locator('#change-residue').click();await page.locator('[data-residue=mulch]').click();await seek(200);ok(await page.evaluate(()=>Fieldnotes.getResult().residueStrategy==='mulch'&&Fieldnotes.getTimeline().sample.residueCover>0&&!Fieldnotes.Scene3D.info().fireVisible),'Mulch recomputes downstream history');await seek(90);ok(await page.evaluate(()=>Fieldnotes.getTimeline().sample.soil.trend==='baseline'&&!Fieldnotes.Scene3D.info().residueVisible),'Rewind restores pre-residue condition');
await page.locator('#language-toggle').click();await page.locator('.menu').click();await page.locator('#theme').click();await page.locator('#close-drawer').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().theme==='dark');ok(await page.evaluate(()=>document.documentElement.lang==='pa'),'Punjabi control changes primary interface');
for(const [w,h] of [[390,844],[390,667],[320,568],[1440,1000]]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:`output/playwright/farmer-dark-pa-${w}-${h}.png`});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Punjabi has no horizontal overflow at '+w+'×'+h);}
await page.reload();ok(await page.evaluate(()=>document.documentElement.lang==='pa'&&document.documentElement.dataset.theme==='dark'),'Theme and language persist');await page.locator('#explore').click();await seek(34.15);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fertilizerVisible),'Fertilizer has a ledger-driven application cue');await page.locator('.menu').click();await page.locator('#motion').click();await seek(34.15);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().windTime===0&&Fieldnotes.Scene3D.info().reduced);const frames=await page.evaluate(()=>Fieldnotes.Scene3D.info().renderedFrames);await page.waitForTimeout(200);ok(await page.evaluate(n=>Fieldnotes.Scene3D.info().renderedFrames===n,frames),'Reduced motion stops repeated rendering');await page.locator('.menu').click();await page.locator('#theme').click();await page.locator('#theme').click();await page.locator('#close-drawer').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().theme==='light');ok(true,'Theme changes redraw a static scene');ok(errors.length===0,'No browser errors');return{passed:checks.length,checks};
}
