async page=>{
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(x,m)=>{if(!x)throw Error(m);checks.push(m)};
await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.removeItem('fasl-language');localStorage.removeItem('fasl-theme')});await page.reload();await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>window.Fieldnotes?.Scene3D.info().renderer);
const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,n)};
await page.locator('[data-scene=wheat]').click();await page.locator('#residue-dialog').waitFor({state:'visible'});ok(await page.evaluate(()=>!Fieldnotes.getTimeline().playing&&Fieldnotes.getTimeline().target===121),'Seeking wheat stops at unanswered harvest choice');await page.screenshot({path:'output/playwright/farmer-choice.png'});
await page.locator('[data-residue=burn]').click();await seek(122);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fireVisible),'Burn path animates fire');await page.screenshot({path:'output/playwright/farmer-fire.png'});await seek(160);ok(await page.evaluate(()=>!Fieldnotes.Scene3D.info().fireVisible&&Fieldnotes.Scene3D.info().residueVisible),'Fire ends and ash persists');
await page.locator('#soil-status').click();ok((await page.locator('#drawer-content').textContent()).includes('5.15'),'Soil details separate research measurements and demonstration assumptions');await page.locator('#change-residue').click();await page.locator('[data-residue=mulch]').click();await seek(200);ok(await page.evaluate(()=>Fieldnotes.getResult().residueStrategy==='mulch'&&Fieldnotes.getTimeline().sample.residueCover>0&&!Fieldnotes.Scene3D.info().fireVisible),'Changing method recalculates mulch and preserves timeline');await seek(90);ok(await page.evaluate(()=>Fieldnotes.getTimeline().sample.soil.trend==='baseline'&&!Fieldnotes.Scene3D.info().residueVisible),'Rewind restores pre-residue condition');
await page.locator('.menu').click();await page.locator('#theme').click();await page.locator('#theme').click();await page.locator('#language').click();await page.locator('#close-drawer').click();await seek(95);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().theme==='dark');ok(await page.evaluate(()=>document.documentElement.lang==='pa'),'Punjabi interface active');
for(const [width,height] of [[390,844],[390,667],[320,568],[1440,1000]]){await page.setViewportSize({width,height});await page.locator('#timeline-slider').blur();await page.screenshot({path:`output/playwright/farmer-dark-pa-${width}.png`});ok(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight),'No page overflow '+width+' × '+height)}
await page.reload();ok(await page.evaluate(()=>document.documentElement.lang==='pa'&&document.documentElement.dataset.theme==='dark'),'Theme and language persist');await page.setViewportSize({width:390,height:844});await seek(34.15);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fertilizerVisible),'Fertilizer transfer is visible');await page.screenshot({path:'output/playwright/farmer-feeding.png'});
await page.locator('.menu').click();await page.locator('#motion').click();await seek(34.15);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().windTime===0);const before=await page.evaluate(()=>Fieldnotes.Scene3D.info().renderedFrames);await page.waitForTimeout(300);ok(await page.evaluate(n=>Fieldnotes.Scene3D.info().renderedFrames===n,before),'Reduced motion stops repeated rendering');await page.locator('.menu').click();await page.locator('#theme').click();await page.locator('#close-drawer').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().theme==='light');ok(true,'Theme changes render even with reduced motion');
ok(errors.length===0,'No JavaScript errors');return {passed:checks.length,checks};
}
