async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
 await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{for(const k of ['fasl-language','fasl-theme','fasl-units','fasl-motion'])localStorage.removeItem(k);});await page.reload();await page.waitForFunction(()=>window.Fieldnotes);
 const state=await page.evaluate(()=>JSON.stringify(Fieldnotes.getResult().state));
 ok(await page.evaluate(()=>Fieldnotes.getTimeline().position===0&&!Fieldnotes.getTimeline().playing),'First visit starts paused at day zero');
 await page.waitForTimeout(200);ok(await page.evaluate(()=>Fieldnotes.getTimeline().position===0),'Welcome does not advance model time');
 await page.locator('[data-choose=rice]').click();await page.locator('#sow-seed').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().journey==='guided');await page.waitForFunction(()=>Fieldnotes.getTimeline().position>1);ok(await page.evaluate(()=>Fieldnotes.getTimeline().journey==='guided'&&Fieldnotes.getTimeline().playing),'Start launches guided story');
 ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().soilScreenY>0),'Story presents crop and underground section directly');
 await page.locator('#play').click();await page.waitForTimeout(100);const paused=await page.evaluate(()=>({p:Fieldnotes.getTimeline().position,t:Fieldnotes.Scene3D.info().windTime}));await page.waitForTimeout(200);
 ok(await page.evaluate(a=>Fieldnotes.getTimeline().position===a.p&&Fieldnotes.Scene3D.info().windTime===a.t,paused),'Pause freezes date and event animation clock');
 const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,n);await page.waitForFunction(n=>Fieldnotes.Scene3D.info().position===n,n);await page.waitForTimeout(120);};
 await seek(45);ok((await page.locator('#stage-title').textContent()).includes('More stems'),'Technical stage names have everyday explanations');
 await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().metrics.mode==='bowl');
 ok(await page.evaluate(()=>Fieldnotes.getTimeline().viewMode==='bowl'&&Fieldnotes.getTimeline().position===45),'Quantity units coordinate camera and preserve date');
 await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend<.02);
 ok(await page.evaluate(()=>Fieldnotes.getTimeline().displayMode==='bowl'&&Fieldnotes.getTimeline().position===45),'Quantity basis and camera remain coordinated at the same date');
 ok(await page.evaluate(s=>JSON.stringify(Fieldnotes.getResult().state)===s,state),'View, units and seeking preserve reducer history');
 await page.locator('[data-scene=wheat]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().sample.id==='wheat');ok(!(await page.locator('#residue-dialog').isVisible()),'Wheat navigation has no mandatory straw modal');
 ok(await page.locator('#baseline-note').textContent().then(s=>s.includes('baseline')),'Retained-straw baseline is disclosed');
 await page.locator('.menu').click();await page.locator('#compare-straw').click();ok((await page.locator('#drawer-content').textContent()).includes('harvests are similar'),'Comparison explains equal yields without an invented bonus');
 await page.locator('#change-residue').click();const beforeChoice=await page.evaluate(()=>Fieldnotes.getTimeline().position);await page.locator('[data-residue=burn]').click();
 ok(await page.evaluate(n=>Fieldnotes.getTimeline().position===n&&Fieldnotes.getTimeline().residueStrategy==='burn',beforeChoice),'Changing straw path preserves the current date');
 await seek(122);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fireVisible),'Burning is visible at its actual event');await seek(90);ok(await page.evaluate(()=>!Fieldnotes.Scene3D.info().fireVisible&&!Fieldnotes.Scene3D.info().residueVisible),'Rewind restores the pre-residue field');
 await page.locator('.menu').click();await page.locator('#compare-straw').click();await page.locator('#change-residue').click();await page.locator('[data-residue=mulch]').click();await seek(200);
 await page.locator('.menu').click();await page.locator('#drawer-content [data-drawer=care]').click();ok((await page.locator('#drawer-content').textContent()).includes('buttons do not apply'),'Care sheet explains automatic care');await page.locator('#drawer-content [data-drawer=fertilizer]').click();ok((await page.locator('#drawer-content').textContent()).includes('Per 100 g dry wheat grain'),'Product details retain correct bowl basis');await page.locator('#close-drawer').click();
 await seek(304);ok(await page.locator('#story-finish').isVisible(),'Final harvest has a conclusion');ok(await page.locator('#harvest-reveal').isVisible(),'Final harvest reveals a dry-food bowl');ok((await page.locator('#metric-grain').textContent())==='100 g','Final bowl uses 100 g dry grain');
 await page.locator('#compare-crops').click();ok((await page.locator('#drawer-content').textContent()).includes('not the total lifecycle water footprint'),'Results distinguish pumping, rain and lifecycle water');await page.locator('#drawer-content [data-drawer=evidence]').click();ok((await page.locator('#drawer-content').textContent()).includes('not a measured'),'Evidence identifies illustrative aquifer storage');await page.locator('#close-drawer').click();
 for(const [w,h] of [[390,844],[390,667],[320,568],[768,1024],[1440,1000]]){await page.setViewportSize({width:w,height:h});await page.locator('#timeline-slider').blur();await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(150);await page.screenshot({path:`output/playwright/journey-ending-${w}-${h}.png`});const l=await page.evaluate(()=>{const b=s=>document.querySelector(s).getBoundingClientRect();return{width:document.documentElement.scrollWidth<=innerWidth,scene:b('#scene-art').height>=340,marker:b('#groundwater-marker').bottom<=b('footer').top,finish:b('#story-finish').top>=b('#harvest-reveal').bottom||b('#story-finish').right<=b('#harvest-reveal').left,range:b('#timeline-slider').bottom<=document.documentElement.scrollHeight};});ok(Object.values(l).every(Boolean),'Readable ending and controls at '+w+'×'+h+' '+JSON.stringify(l));}
 await page.locator('#language-toggle').click();ok(await page.evaluate(()=>document.documentElement.lang==='pa'),'Visible language control switches to Punjabi');await page.locator('.menu').click();await page.locator('#theme').click();await page.locator('#theme').click();await page.locator('#close-drawer').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().theme==='dark');await page.screenshot({path:'output/playwright/journey-punjabi-dark.png'});
 await page.reload();ok(await page.evaluate(()=>document.documentElement.lang==='pa'&&document.documentElement.dataset.theme==='dark'),'Language and theme persist on reload');
 await page.locator('[data-choose=rice]').click();await page.locator('#sow-seed').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().journey==='guided');await page.locator('#play').click();await page.locator('.menu').click();await page.locator('#motion').click();await seek(250);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().windTime===0&&Fieldnotes.Scene3D.info().reduced);ok(await page.evaluate(()=>!Fieldnotes.getTimeline().playing),'Reduced motion remains paused');await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend===0);await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().zoomBlend===1);ok(true,'Reduced motion switches camera immediately');
 const frames=await page.evaluate(()=>Fieldnotes.Scene3D.info().renderedFrames);await page.waitForTimeout(200);ok(await page.evaluate(n=>Fieldnotes.Scene3D.info().renderedFrames===n,frames),'Reduced motion stops repeated rendering');
 await page.locator('#timeline-slider').press('ArrowRight');await page.waitForFunction(()=>Fieldnotes.getTimeline().target===251);ok(true,'Keyboard timeline navigation advances one day');
 await page.locator('#timeline-slider').press('End');await page.waitForFunction(()=>Fieldnotes.getTimeline().position===304);await page.locator('#replay').click();ok(await page.evaluate(()=>Fieldnotes.getTimeline().journey==='guided'&&Fieldnotes.getTimeline().position<2),'Replay restarts the guided journey');
 ok(errors.length===0,'No browser JavaScript errors');return{passed:checks.length,checks};
}
