async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
 await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');localStorage.removeItem('fasl-motion');});await page.reload();await page.locator('[data-choose=rice]').click();await page.locator('#sow-seed').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().journey==='guided');await page.locator('#play').click();await page.waitForFunction(()=>window.Fieldnotes?.Scene3D.info().renderer);
 const data=await page.evaluate(()=>{const r=Fieldnotes.getResult();return{rainDay:r.snapshots.find(s=>s.day>27&&s.rainMm>0).day,pumpDay:r.snapshots.find(s=>s.day>27&&s.lastFlows.pumped>0&&s.lastFlows.infiltration>0).day,rechargeDay:r.snapshots.find(s=>s.day>27&&s.lastFlows.recharge>s.lastFlows.pumped).day,conserved:r.state.maxBalanceError<1e-7,unresolved:r.snapshots.flatMap(s=>s.checkpoints).filter(c=>!c.resolved).length};});
 ok(data.conserved&&data.unresolved===0,'Both seasons resolve automatic care and conserve water');
 const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Fieldnotes.getTimeline().position===n&&Fieldnotes.Scene3D.info().position===n,n);};
 await seek(35.5);const before=await page.evaluate(()=>Fieldnotes.Scene3D.info());await page.waitForTimeout(200);const after=await page.evaluate(()=>Fieldnotes.Scene3D.info());ok(after.windTime===before.windTime&&after.geometryBuilds===before.geometryBuilds,'Paused crops freeze wind without rebuilding geometry');
 await seek(data.pumpDay+.22);const pool=await page.evaluate(()=>Fieldnotes.Scene3D.info().surfacePoolHeight);ok(pool>.008&&await page.evaluate(()=>Fieldnotes.Scene3D.info().dischargeAnimating),'Recorded pumping has discharge and surface ponding');
 await seek(data.pumpDay+.68);ok(await page.evaluate(h=>Fieldnotes.Scene3D.info().surfacePoolHeight<h&&Fieldnotes.getTimeline().sample.flow.infiltration>0,pool),'Surface water infiltrates during the sampled daily phase');
 await seek(data.rainDay+.2);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().rainAnimating&&Fieldnotes.Scene3D.info().cloudsVisible),'Recorded rain has static cloud/rain cues while paused');
 await seek(data.rechargeDay);const lower=await page.evaluate(()=>Fieldnotes.getTimeline().sample.aquiferL);await seek(data.rechargeDay+.25);ok(await page.evaluate(n=>Fieldnotes.getTimeline().sample.aquiferL>n,lower),'Groundwater rises on recorded arriving recharge');
 await seek(34.15);ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().fertilizerVisible),'Granular fertilizer follows the sampled application day');
 await page.locator('.menu').click();await page.locator('#drawer-content [data-drawer=care]').click();await page.locator('#drawer-content [data-drawer=fertilizer]').click();ok((await page.locator('#drawer-content').textContent()).includes('urea'),'Care sheet exposes the product ledger');await page.locator('#close-drawer').click();
 const state=await page.evaluate(()=>JSON.stringify(Fieldnotes.getResult().state));await seek(0);await seek(95);ok(await page.evaluate(s=>JSON.stringify(Fieldnotes.getResult().state)===s,state),'Reverse seeking never applies inputs twice');
 for(const [w,h] of [[390,844],[390,667],[320,568],[1440,1000]]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:`output/playwright/live-${w}-${h}.png`});ok(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.querySelector('#groundwater-marker').getBoundingClientRect().bottom<document.querySelector('footer').getBoundingClientRect().top),'Field and groundwater stay clear at '+w+'×'+h);}
 await page.locator('[data-scene=wheat]').click();await page.waitForFunction(()=>Fieldnotes.Scene3D.info().crop==='wheat');ok(!(await page.locator('#residue-dialog').isVisible()),'Wheat navigation uses the disclosed baseline directly');
 await page.locator('.menu').click();await page.locator('#motion').click();await seek(200.5);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().windTime===0&&Fieldnotes.Scene3D.info().reduced);ok(true,'Reduced motion retains model state and removes wind');await page.locator('#timeline-slider').press('ArrowRight');await page.waitForFunction(()=>Fieldnotes.getTimeline().target===201.5);ok(true,'Keyboard advances one day');
 ok(errors.length===0,'No browser errors');return{passed:checks.length,checks};
}
