async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
 await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-theme','light');});await page.reload();await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>window.Fieldnotes?.Scene3D.info().renderer);
 await page.getByRole('button',{name:'Pause simulation',exact:true}).click();
 const data=await page.evaluate(()=>{const r=Fieldnotes.getResult();return {rainDay:r.snapshots.find(s=>s.day>27&&s.rainMm>0).day,pumpDay:r.snapshots.find(s=>s.day>27&&s.lastFlows.pumped>0&&s.lastFlows.infiltration>0).day,rechargeDay:r.snapshots.find(s=>s.day>27&&s.lastFlows.recharge>s.lastFlows.pumped).day,wheat:Fieldnotes.Sim.wheatStart(),unresolved:r.snapshots.flatMap(s=>s.checkpoints).filter(c=>!c.resolved).length,conserved:r.state.maxBalanceError<1e-7};});
 ok(data.unresolved===0&&data.conserved,'Both seasons run automatically without unresolved choices and retain water conservation');
 const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,n);};
 await seek(95.5);const grown=await page.evaluate(()=>({info:Fieldnotes.Scene3D.info(),bottle:Number(document.querySelector('#fert-icon').dataset.remaining)}));
 ok(grown.bottle===0,'The plant-food bottle empties after all scheduled applications');
 await page.locator('#timeline-slider').fill('35.5');const during=await page.evaluate(()=>Fieldnotes.getTimeline().position);ok(during>35.5&&during<95.5,'Scrubbing interpolates through intermediate time instead of swapping snapshots');await page.waitForFunction(()=>Math.abs(Fieldnotes.getTimeline().position-35.5)<.001);
 const frames=await page.evaluate(()=>Fieldnotes.Scene3D.info());await page.waitForFunction(n=>Fieldnotes.Scene3D.info().renderedFrames>n+15,frames.renderedFrames);
 const moving=await page.evaluate(()=>Fieldnotes.Scene3D.info());ok(moving.windTime>frames.windTime&&moving.geometryBuilds===1,'Paused plants keep moving in the breeze using one stable geometry');
 await seek(0);ok(await page.evaluate(()=>Number(document.querySelector('#fert-icon').dataset.remaining)>.99),'Scrubbing backward restores the input inventory');
 await seek(data.pumpDay+.22);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().dischargeAnimating&&Fieldnotes.Scene3D.info().surfacePoolHeight>.008);const pondBefore=await page.evaluate(()=>Fieldnotes.Scene3D.info().surfacePoolHeight);await page.screenshot({path:'output/playwright/live-pumping.png'});
 await seek(data.pumpDay+.68);await page.waitForFunction(h=>Fieldnotes.Scene3D.info().surfacePoolHeight<h,pondBefore);
 const pondAfter=await page.evaluate(()=>Fieldnotes.getTimeline().sample.pondDepthMm);ok(pondAfter>=0&&await page.evaluate(()=>Fieldnotes.getTimeline().sample.flow.infiltration>0),'Pump discharge becomes surface water before infiltrating');
 await seek(data.rainDay+.2);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().rainAnimating&&Fieldnotes.Scene3D.info().cloudsVisible);await page.screenshot({path:'output/playwright/live-rain.png'});ok(true,'Recorded rain has animated clouds, falling rain and a surface pool');
 await seek(data.rechargeDay);const lower=await page.evaluate(()=>Fieldnotes.getTimeline().sample.aquiferL);await seek(data.rechargeDay+.25);const higher=await page.evaluate(()=>Fieldnotes.getTimeline().sample.aquiferL);ok(higher>lower&&await page.locator('#groundwater-label').textContent().then(s=>s.includes('↑')),'Groundwater marker rises on arriving recharge');
 let full=await page.evaluate(()=>JSON.stringify(Fieldnotes.getResult().state));await seek(95.5);await page.locator('#timeline-slider').blur();
 for(const [width,height] of [[390,844],[390,667],[1440,1000]]){await page.setViewportSize({width,height});await page.waitForFunction(()=>document.querySelector('canvas').getBoundingClientRect().height===innerHeight);const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight,range:document.querySelector('#timeline-slider').getBoundingClientRect().bottom<=innerHeight,marker:getComputedStyle(document.querySelector('#groundwater-marker')).display!=='none'}));ok(Object.values(layout).every(Boolean),`${width} × ${height}: full-screen plot, bottom slider and groundwater marker`);await page.screenshot({path:`output/playwright/live-${width}-${height}.png`});}
 await page.getByRole('button',{name:'Wheat',exact:true}).click();await page.locator('[data-residue=mulch]').click();await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,data.wheat);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().crop==='wheat');ok(await page.evaluate(()=>Fieldnotes.Scene3D.info().crop==='wheat'),'Wheat inherits the same rotation groundwater');
 full=await page.evaluate(()=>JSON.stringify(Fieldnotes.getResult().state));await page.getByRole('button',{name:'Settings and information',exact:true}).click();await page.locator('#motion').click();await seek(200.5);await page.waitForFunction(()=>Fieldnotes.Scene3D.info().windTime===0);const still=await page.evaluate(()=>Fieldnotes.Scene3D.info());ok(still.windTime===0&&await page.evaluate(()=>JSON.stringify(Fieldnotes.getResult().state))===full,'Reduced motion stops decorative motion without changing the simulation');
 await page.locator('#timeline-slider').press('ArrowRight');ok(await page.evaluate(()=>Fieldnotes.getTimeline().target===201.5),'Keyboard navigation advances one day on the continuous slider');
 ok(errors.length===0,'No browser JavaScript errors');return{passed:checks.length,checks,drawCalls:grown.info.drawCalls};
}
