const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const DATA=Object.fromEntries(fs.readdirSync('data').filter(f=>f.endsWith('.json')).map(f=>[f.slice(0,-5),JSON.parse(fs.readFileSync('data/'+f))]));const ctx={DATA};vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/simulation.js','utf8')+';this.Sim=Sim;'+fs.readFileSync('app/timeline.js','utf8')+';this.Timeline=Timeline;',ctx);const {Sim,Timeline}=ctx;
const burn=Sim.ideal({residueStrategy:'burn'}),mulch=Sim.ideal({residueStrategy:'mulch'});
assert.equal(JSON.stringify(burn.snapshots.slice(0,121)),JSON.stringify(mulch.snapshots.slice(0,121)));
for(const r of [burn,mulch]){assert.ok(r.state.maxBalanceError<1e-7);assert.equal(r.state.events.filter(e=>e.type==='residue_management').length,1);assert.ok(r.state.cropStates.wheat.harvested);assert.equal(JSON.stringify(r.state),JSON.stringify(Sim.ideal({residueStrategy:r.residueStrategy}).state));for(const c of Object.values(r.state.cropStates)){const ids=c.products.map(p=>p.id);assert.equal(ids.length,new Set(ids).size);}}
assert.ok(mulch.state.water.et<burn.state.water.et);assert.ok(mulch.state.water.pumped<burn.state.water.pumped);assert.ok(mulch.state.soil.residueNReturned>0);assert.equal(burn.state.soil.residueNReturned,0);assert.equal(burn.state.soil.trend,'declining');assert.equal(mulch.state.soil.trend,'improving');
const n=mulch.state.cropStates.rice.products.concat(mulch.state.cropStates.wheat.products).filter(p=>p.category==='fertilizer').reduce((n,p)=>n+p.quantity*(Sim.CONFIG.demonstration.compositions[p.product]||0),0);assert.equal(n,mulch.state.soil.fertilizerN);
const flows=Timeline.prepare(mulch),a=Timeline.sample(mulch,flows,34.1),b=Timeline.sample(mulch,flows,34.2);assert.ok(b.soil.fertilizerN>a.soil.fertilizerN);assert.equal(JSON.stringify(a),JSON.stringify(Timeline.sample(mulch,flows,34.1)));assert.throws(()=>Sim.ideal({residueStrategy:'invalid'}));
console.log('PASS residue branches: shared history, conservation, determinism, pumping response, nitrogen units, interpolation and unique applications');console.log(JSON.stringify({burnPumping:burn.state.water.pumped,mulchPumping:mulch.state.water.pumped,burnWheat:burn.state.cropStates.wheat.edibleKg,mulchWheat:mulch.state.cropStates.wheat.edibleKg}));
