const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const DATA=Object.fromEntries(fs.readdirSync('data').filter(f=>f.endsWith('.json')).map(f=>[f.slice(0,-5),JSON.parse(fs.readFileSync('data/'+f))]));
const ctx={DATA,module:{exports:{}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/simulation.js','utf8'),ctx);const {Sim}=ctx.module.exports;
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}const near=(a,b,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
function managed(seed=126826,scenario='normal'){let actions={},r;for(let day=0;day<=Sim.endDay();day++){
  r=Sim.simulate({seed,scenario,day,actions});const s=r.state,c=s.cropStates[s.cropId];
  if(c&&s.das%7===0&&s.zones.find(z=>z.crop===s.cropId)?.soil/s.zones.find(z=>z.crop===s.cropId).area<85)actions[day+':water']='50';
  r=Sim.simulate({seed,scenario,day,actions});for(const cp of r.state.checkpoints)actions[day+':'+cp.key]=cp.key==='establish'?'sow':cp.key==='transplant'?'transplant':cp.key==='weed'?'manual':cp.key==='pest'?'monitor':cp.key==='water'?(actions[day+':water']||'wait'):'full';
}return{actions,result:Sim.simulate({seed,scenario,day:Sim.endDay(),actions})};}
const normal=managed();
test('determinism: full rotation, inputs, weather, yield, stocks',()=>{assert.equal(JSON.stringify(normal.result.state),JSON.stringify(Sim.simulate({day:Sim.endDay(),actions:normal.actions}).state));});
test('monthly rain totals in all scenarios and years',()=>{for(const scenario of ['normal','dry','wet']){const w=Sim.weather(126826,scenario);for(const y of [2027,2028])for(let m=1;m<=12;m++){const prefix=y+'-'+String(m).padStart(2,'0'),sum=Object.entries(w).filter(([d])=>d.startsWith(prefix)).reduce((n,[d,v])=>n+v,0);near(sum,DATA.rainfall.months[m-1].rain_mm*Sim.CONFIG.dry_wet_rain_multipliers[scenario],1e-9);}}});
test('daily and whole-rotation conservation including transitions and pending recharge',()=>{const r=normal.result;for(const s of r.snapshots){assert.ok(s.maxBalanceError<1e-7);near(Sim.stocks(s),s.initialStocks+s.water.rain-s.water.et-s.water.runoff-s.water.conveyance-s.water.deep-s.water.overflow,1e-6);near(s.aquifer,Sim.H.aquifer_initial_L+s.water.recharge-s.water.pumped-s.water.overflow,1e-6);}});
test('nursery and fallow rain cover one acre once; no full-acre nursery pumping',()=>{let r=Sim.simulate({day:26,actions:{'0:water':'50'}});near(r.state.cropStates.rice.water.pumped,50*160/.8);for(const s of r.snapshots){const events=s.events.filter(e=>e.date===s.date&&e.type==='rain');near(events.reduce((n,e)=>n+e.quantity,0),s.rainMm*Sim.A);near(events.find(e=>e.cropId==='rice').quantity,s.rainMm*160);}});
test('reducer unique day IDs prevent double counting',()=>{const s=normal.result.state;assert.strictEqual(Sim.reduce(s,{type:'day',id:'day:'+s.day,day:s.day},{}),s);assert.equal(new Set(s.events.map(e=>e.id)).size,s.events.length);});
test('aquifer exhaustion, spray limitations and accounted overflow',()=>{const cfg=Sim.clone(Sim.CONFIG);cfg.hydrology.aquifer_initial_L=20;const s=Sim.simulate({cfg,day:0,actions:{'0:water':'75'}}).state;near(s.water.pumped,20);near(s.aquifer,0);assert.ok(s.maxBalanceError<1e-7);const cap=Sim.clone(Sim.CONFIG);cap.hydrology.aquifer_capacity_L=cap.hydrology.aquifer_initial_L;const r=Sim.simulate({cfg:cap,day:60,scenario:'wet'});assert.ok(r.state.water.overflow>0);assert.ok(r.state.maxBalanceError<1e-7);});
test('25% wheat border application scales formulation and carrier',()=>{let day=Sim.wheatStart()+110,actions={'0:establish':'sow'};let r=Sim.simulate({day,actions,seed:3});const occurred=r.snapshots.find(s=>s.cropId==='wheat'&&s.cropStates.wheat.pest>0);assert.ok(occurred);day=occurred.day;actions[day+':scout']='inspect';actions[day+':pest']='chemical';r=Sim.simulate({seed:3,day,actions});const p=r.state.cropStates.wheat.products.find(p=>p.productId==='wheat_aphid');assert.ok(p);near(p.quantity,5);near(p.sprayWaterL,22.5);near(p.treatedAreaFraction,.25);});
test('skip is zero quantity; zero-pest run uses zero treatments',()=>{const s=Sim.simulate({day:Sim.endDay(),actions:{'0:fert0':'skip'}}).state;assert.equal(s.cropStates.rice.products.length,0);assert.equal(s.cropStates.wheat.products.length,0);});
test('wheat urea triggers/deadline doses are never repeated by later irrigation',()=>{const ws=Sim.wheatStart(),actions={[ws+':dap']:'full',[ws+35+':urea1']:'full',[ws+55+':urea2']:'full',[ws+65+':water']:'75',[ws+90+':water']:'75'};const c=Sim.simulate({day:ws+100,actions}).state.cropStates.wheat;assert.equal(c.products.filter(p=>p.product==='urea').length,2);near(c.products.filter(p=>p.product==='urea').reduce((n,p)=>n+p.quantity,0),90);});
test('branch recomputes downstream rice, fallow and wheat without duplicate events',()=>{const changed={...normal.actions,'34:fert34':'skip','48:water':'75'},r=Sim.simulate({day:Sim.endDay(),actions:changed});assert.notEqual(r.state.cropStates.rice.actualYieldKg,normal.result.state.cropStates.rice.actualYieldKg);assert.notEqual(r.snapshots[Sim.wheatStart()].aquifer,normal.result.snapshots[Sim.wheatStart()].aquifer);assert.ok(r.state.maxBalanceError<1e-7);assert.equal(r.state.cropStates.rice.products.filter(p=>p.id==='48:fert48:urea').length,1);});
test('dry-food numerical fixtures, units and zero-harvest safe allocation',()=>{const rice=Sim.initial(Sim.CONFIG).cropStates.rice;rice.harvested=true;rice.edibleKg=3000*.67;rice.water.pumped=1e6;const a=Sim.allocation(rice);near(a.kg,2010);near(a.bowls,20100);near(a.pumpedPerBowl,49.75124378109453);const w=Sim.initial(Sim.CONFIG).cropStates.wheat;w.harvested=true;w.edibleKg=2400;w.water.pumped=1e6;near(Sim.allocation(w).pumpedPerBowl,41.666666666666664);near(Sim.A,4046.8564224);rice.edibleKg=0;assert.equal(Sim.allocation(rice).pumpedPerBowl,null);const no=Sim.simulate({day:120,actions:{'0:establish':'unsown','0:fert0':'full','0:water':'50'}}).state.cropStates.rice;near(no.edibleKg,0);assert.ok(no.water.pumped>0);assert.ok(no.products.length>0);});
test('calendar UTC anchors and wheat harvest',()=>{assert.equal(Sim.dateAt(27),'2027-07-05');assert.equal(Sim.dateAt(120),'2027-10-06');assert.equal(Sim.dateAt(Sim.wheatStart()),'2027-11-10');assert.equal(Sim.dateAt(Sim.endDay()),'2028-04-06');});
test('validated import uses decisions and rejects malformed or dangerous inputs',()=>{const valid={schemaVersion:'1.0',datasetVersion:'package-1.0',randomSeed:126826,horizon:Sim.endDay(),scenario:'normal',assumptions:Sim.CONFIG,decisions:normal.actions,cumulativeWaterLedger:{pumped:123}};const r=Sim.validateImport(valid);near(Sim.simulate(r).state.aquifer,normal.result.state.aquifer);for(const mutation of [{schemaVersion:'9'},{randomSeed:Infinity},{horizon:-1},{cumulativeWaterLedger:{pumped:-2}},{decisions:{'0:water':'-25'}},{decisions:JSON.parse('{"__proto__":{"evil":true}}')},{assumptions:{}}])assert.throws(()=>Sim.validateImport({...valid,...mutation}));});
console.log(`${checks} acceptance groups passed.`);
