async page=>{
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m);};
await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-units','acre');localStorage.setItem('fasl-theme','light');localStorage.removeItem('fasl-motion');});await page.reload();await page.locator('[data-choose=rice]').click();await page.locator('#sow-seed').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().journey==='guided');await page.locator('#play').click();
const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Fieldnotes.getTimeline().position===n&&Fieldnotes.Scene3D.info().position===n,n);await page.waitForTimeout(120);};
await seek(34.15);const before=await page.evaluate(()=>({state:JSON.stringify(Fieldnotes.getResult().state),target:Fieldnotes.getTimeline().target,metrics:Fieldnotes.getTimeline().metrics}));await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().metrics.mode==='bowl');const after=await page.evaluate(()=>({target:Fieldnotes.getTimeline().target,metrics:Fieldnotes.getTimeline().metrics,view:Fieldnotes.getTimeline().viewMode}));ok(after.target===before.target&&after.view==='bowl','Unit switch preserves date and coordinates crop view');ok(Math.abs(after.metrics.pumpedL-before.metrics.pumpedL*after.metrics.scale)<1e-7,'Pumping scales to the same crop output');ok(await page.evaluate(s=>JSON.stringify(Fieldnotes.getResult().state)===s,before.state),'Unit switch preserves reducer state');
await page.locator('.menu').click();await page.locator('#drawer-content [data-drawer=care]').click();await page.locator('#drawer-content [data-drawer=fertilizer]').click();const input=await page.locator('#drawer-content').textContent();ok(input.includes('Per 100 g dry rice')&&!input.includes('${'),'Product ledger renders correct bowl basis');ok(input.includes(' g'),'Solid products convert to grams');await page.locator('#close-drawer').click();await seek(95);ok((await page.locator('#metric-grain').textContent()).includes(' g'),'Forming grain uses grams');
for(const [w,h] of [[390,844],[390,667],[320,568],[1440,1000]]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:`output/playwright/ux-metrics-${w}-${h}.png`});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.live-metrics').getBoundingClientRect().right<=innerWidth),'Metric controls fit '+w+'×'+h);}
await page.locator('[data-scene=wheat]').click();await seek(200);ok(await page.evaluate(()=>Fieldnotes.getTimeline().metrics.plants>0),'Wheat has dynamic modeled population in details');await seek(304);ok((await page.locator('#metric-grain').textContent())==='100 g','Wheat harvest gives 100 g dry bowl');ok(await page.evaluate(()=>Fieldnotes.getTimeline().metrics.plants===0),'Harvest removes standing plants');await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().metrics.mode==='acre');await page.reload();ok(await page.evaluate(()=>Fieldnotes.getTimeline().displayMode==='acre'),'Quantity preference persists');ok(errors.length===0,'No browser errors');return{passed:checks.length,checks};
}
