async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(b,m)=>{if(!b)throw Error(m);checks.push(m)};
 await page.goto('http://127.0.0.1:8080/');await page.evaluate(()=>{localStorage.setItem('fasl-language','en');localStorage.setItem('fasl-units','acre');localStorage.setItem('fasl-theme','light')});await page.reload();await page.waitForFunction(()=>window.Fieldnotes?.Scene3D.info().renderer);
 const seek=async n=>{await page.locator('#timeline-slider').fill(String(n));await page.waitForFunction(n=>Math.abs(Fieldnotes.getTimeline().position-n)<.001,n)};
 await seek(34.15);const before=await page.evaluate(()=>({state:JSON.stringify(Fieldnotes.getResult().state),target:Fieldnotes.getTimeline().target,metrics:Fieldnotes.getTimeline().metrics}));await page.locator('[data-unit=bowl]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().metrics.mode==='bowl');const after=await page.evaluate(()=>Fieldnotes.getTimeline());ok(after.target===before.target,'Unit toggle preserves date');ok(Math.abs(after.metrics.pumpedL-before.metrics.pumpedL*after.metrics.scale)<1e-7,'Water scales to same crop output');ok(await page.evaluate(state=>JSON.stringify(Fieldnotes.getResult().state)===state,before.state),'Unit toggle preserves model');
 await page.locator('[data-drawer=fertilizer]').click();ok(!(await page.locator('#drawer-content').textContent()).includes('${'),'Input drawer renders real basis labels');ok((await page.locator('#drawer-content').textContent()).includes('Per 100 g dry rice'),'Product ledger uses bowl units');await page.locator('#close-drawer').click();await seek(95);ok(await page.locator('#metric-grain').textContent().then(s=>s.includes(' g')),'Grain uses grams in bowl mode');
 for(const [width,height] of [[390,844],[390,667],[320,568],[1440,1000]]){await page.setViewportSize({width,height});await page.waitForFunction(()=>document.querySelector('canvas').getBoundingClientRect().height===innerHeight);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.locator('#timeline-slider').blur();await page.screenshot({path:`output/playwright/ux-metrics-${width}-${height}.png`});const layout=await page.evaluate(()=>{const $=s=>document.querySelector(s).getBoundingClientRect(),a=$('.inputs'),f=$('footer'),u=$('.unit-switch');return{center:Fieldnotes.Scene3D.info().cropCenterX,overflow:document.documentElement.scrollWidth>innerWidth,inputClear:a.bottom<f.top,unitsClear:u.bottom<a.top,markerClear:$('#groundwater-marker').bottom<f.top};});ok(Math.abs(layout.center)<.001,'Crop centered '+width);ok(!layout.overflow&&layout.inputClear&&layout.unitsClear&&layout.markerClear,'Controls and groundwater clear of timeline '+width+'×'+height)}
 await page.locator('[data-scene=wheat]').click();await page.locator('[data-residue=mulch]').click();await seek(200);ok(await page.locator('#metric-plants').textContent().then(s=>parseFloat(s)>0),'Wheat has dynamic population');await seek(304);ok(await page.locator('#metric-grain').textContent().then(s=>s==='100 g'),'Wheat harvest gives 100 g dry bowl');ok(await page.locator('#metric-plants').textContent().then(s=>parseFloat(s)===0),'Harvest removes standing plants');
 await page.locator('[data-unit=acre]').click();await page.waitForFunction(()=>Fieldnotes.getTimeline().metrics.mode==='acre');await page.reload();ok(await page.evaluate(()=>Fieldnotes.getTimeline().displayMode==='acre'),'Unit choice persists');ok(errors.length===0,'No browser errors');return{passed:checks.length,checks};
}
