'use strict';
const $=id=>document.getElementById(id),fmt=(n,d=1)=>Number(n).toLocaleString('en',{maximumFractionDigits:d}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let result=Sim.ideal(),flows=Timeline.prepare(result);const maxDay=result.snapshots.length;let residueStrategy=null,pendingSeek=null,resumeAfterChoice=false;
const readPref=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
let language=readPref('fasl-language','en'),theme=readPref('fasl-theme','system'),displayMode=readPref('fasl-units','acre');
if(!['acre','bowl'].includes(displayMode))displayMode='acre';
const savePref=(key,value)=>{try{localStorage.setItem(key,value);}catch{}};
const tr=(en,pa)=>language==='pa'?pa:en;
const locale=()=>language==='pa'?'pa-IN':'en';
const paMonths=['ਜਨਵਰੀ','ਫ਼ਰਵਰੀ','ਮਾਰਚ','ਅਪ੍ਰੈਲ','ਮਈ','ਜੂਨ','ਜੁਲਾਈ','ਅਗਸਤ','ਸਤੰਬਰ','ਅਕਤੂਬਰ','ਨਵੰਬਰ','ਦਸੰਬਰ'];
function displayDate(date,year=false){return language==='pa'?date.getUTCDate()+' '+paMonths[date.getUTCMonth()]+(year?' '+date.getUTCFullYear():''):date.toLocaleDateString('en',{day:'numeric',month:'short',...(year?{year:'numeric'}:{}),timeZone:'UTC'});}
let position=0,target=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,lastTime=0,uiTime=0,current,dragging=false;
const speed=1.5;
// No old decision-game save is loaded or overwritten by this automatic demonstration.
const planned={};for(const id of ['rice','wheat']){const crop=result.state.cropStates[id];planned[id]={};for(const cat of ['fertilizer','herbicide','pest_control'])planned[id][cat]=crop.products.filter(p=>p.category===cat).reduce((n,p)=>n+p.quantity,0);}
function bottle(key,label,color){return `<svg viewBox="0 0 48 68" aria-hidden="true"><defs><clipPath id="clip-${key}"><path d="M14 16h20l5 8v36q-15 6-30 0V24z"/></clipPath></defs><path d="M14 8h20v9l5 7v36q-15 6-30 0V24l5-7z" fill="#e8e6d1" fill-opacity=".65" stroke="#9aaa89"/><g clip-path="url(#clip-${key})"><rect class="bottle-liquid" x="8" y="17" width="32" height="47" fill="${color}" opacity=".8"/></g><path d="M15 7h19v7H15z" fill="#637953"/><path d="M13 29h23v21H13z" fill="#f3f0dd" opacity=".85"/><text x="24" y="43" text-anchor="middle" font-family="Georgia" font-size="14" fill="#657856">${label}</text><path d="M12 25v29" stroke="#fff" opacity=".65"/></svg>`;}
for(const [id,label,color] of [['fert','N','#a8ad67'],['weed','W','#8ea67f'],['pest','P','#c5b58c']])$(id+'-icon').innerHTML=bottle(id,label,color);
const monthMarks=[];const first=new Date(Sim.dateAt(0)+'T00:00:00Z');let month=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,1));monthMarks.push({day:0,label:'Jun',key:'2027-06'});while(month<=new Date(Sim.dateAt(maxDay)+'T00:00:00Z')){const day=(month-first)/Sim.MS;monthMarks.push({day,label:month.toLocaleDateString(locale(),{month:'short',timeZone:'UTC'}),key:month.toISOString().slice(0,7)});month=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,1));}
$('timeline-slider').max=maxDay;$('month-list').innerHTML=monthMarks.map(m=>`<span style="left:${m.day/maxDay*100}%" data-month="${m.key}">${m.label}</span>`).join('');$('timeline-ticks').innerHTML=monthMarks.map(m=>`<i style="left:${m.day/maxDay*100}%"></i>`).join('');
function liters(n){return n>=1e6?fmt(n/1e6,2)+'M L':n>=1000?fmt(n/1000,1)+'k L':fmt(n,0)+' L';}
function updateUI(v){
 const m=Metrics.sample(result,v,displayMode);
 document.querySelectorAll("[data-unit]").forEach(b=>b.setAttribute("aria-pressed",b.dataset.unit===displayMode));
 $("metric-plants").textContent=count(m.plants);$("metric-water").textContent=liters(m.pumpedL);$("metric-grain").textContent=mass(m.grainKg);
 $("label-plants").textContent=tr("Plants ≈","ਪੌਦੇ ≈");$("label-water").textContent=tr("Pumped","ਪੰਪ ਕੀਤਾ");$("label-grain").textContent=tr(m.harvested?"Harvested grain":"Grain forming",m.harvested?"ਵਾਢੀ ਦਾ ਅਨਾਜ":"ਬਣ ਰਿਹਾ ਅਨਾਜ");
 const date=new Date(Sim.dateAt(v.day)+'T00:00:00Z'),stage=v.fallow?tr('Between seasons','ਦੋ ਫ਼ਸਲਾਂ ਵਿਚਕਾਰ'):stageLabel(v);
 $('stage-title').textContent=stage;$('current-date').textContent=displayDate(date,true);
 $('timeline-caption').textContent=(v.fallow?tr('Between seasons','ਦੋ ਫ਼ਸਲਾਂ ਵਿਚਕਾਰ'):tr(v.def.name,v.id==='rice'?'ਝੋਨਾ':'ਕਣਕ'))+' · '+displayDate(date);
 $('timeline-slider').value=target;$('timeline-slider').style.setProperty('--progress',position/maxDay*100+'%');$('timeline-slider').setAttribute('aria-valuetext',`${displayDate(date)}, ${stage}`);
 document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scene===v.id&&!v.fallow));document.querySelectorAll('[data-month]').forEach(m=>m.classList.toggle('current-month',m.dataset.month===Sim.dateAt(v.day).slice(0,7)));
 $('play').textContent=playing?'Ⅱ':'▷';$('play').title=tr(playing?'Pause':'Play',playing?'ਰੋਕੋ':'ਚਲਾਓ');$('play').setAttribute('aria-label',tr(playing?'Pause simulation':'Play simulation',playing?'ਸਿਮੂਲੇਸ਼ਨ ਰੋਕੋ':'ਸਿਮੂਲੇਸ਼ਨ ਚਲਾਓ'));
 $('pump-used').textContent=liters(m.pumpedL)+' '+tr('pumped','ਪੰਪ ਕੀਤਾ');const effects=Scene3D.info();document.querySelector('.pump-state').classList.toggle('running',effects.pumpStrength>.05);
 $('weather-status').textContent=effects.rainStrength>.1&&v.flow.rain>0?tr('Rain · ','ਮੀਂਹ · ')+fmt(v.s.rainMm,1)+' mm':effects.pumpStrength>.1?tr('Tubewell watering','ਟਿਊਬਵੈੱਲ ਸਿੰਚਾਈ'):effects.infiltrationAnimating?tr('Water seeping into soil','ਪਾਣੀ ਮਿੱਟੀ ਵਿੱਚ ਰਿਸ ਰਿਹਾ ਹੈ'):v.flow.recharge>0?tr('Groundwater recharging','ਧਰਤੀ ਹੇਠਲੇ ਪਾਣੀ ਦੀ ਭਰਪਾਈ'):v.flow.queuedRecharge>0&&v.fraction>.8?tr('Drainage toward groundwater','ਪਾਣੀ ਹੇਠਾਂ ਵੱਲ ਰਿਸ ਰਿਹਾ ਹੈ'):v.fallow?tr('The soil rests','ਮਿੱਟੀ ਨੂੰ ਆਰਾਮ'):tr('A breeze through the field','ਖੇਤ ਵਿੱਚ ਹਲਕੀ ਹਵਾ');
 for(const [id,cat] of [['fert','fertilizer'],['weed','herbicide'],['pest','pest_control']]){const capacity=planned[v.id][cat],remaining=capacity?Math.max(0,1-v.totals[cat]/capacity):1,liquid=$(id+'-icon').querySelector('.bottle-liquid');liquid.setAttribute('height',47*remaining);liquid.setAttribute('y',64-47*remaining);$(id+'-icon').dataset.remaining=remaining;$(id+'-icon').closest('button').title=capacity?fmt(remaining*100,0)+tr('% of this season’s planned inputs remaining','% ਇਸ ਮੌਸਮ ਦੀ ਬਾਕੀ ਮਾਤਰਾ'):tr('No treatment needed this season','ਇਸ ਮੌਸਮ ਵਿੱਚ ਇਲਾਜ ਦੀ ਲੋੜ ਨਹੀਂ');}
 $('soil-status').textContent=tr('Soil','ਮਿੱਟੀ')+' · '+soilLabel(v.soil.trend);
 const prev=v.previous.aquifer,diff=v.aquiferL-prev;$('groundwater-label').textContent=(Math.abs(diff)<.5?'↔':diff>0?'↑':'↓')+' '+tr('Groundwater · ','ਧਰਤੀ ਹੇਠਲਾ ਪਾਣੀ · ')+fmt(v.aquiferL/Sim.H.aquifer_capacity_L*100,1)+'%';
}
function jump(value){if(!residueStrategy&&value>121){pendingSeek=value;resumeAfterChoice=false;chooseResidue();value=121;}playing=false;target=Math.max(0,Math.min(maxDay,value));if(reduced)position=target;uiTime=0;}
$('timeline-slider').addEventListener('input',e=>{dragging=true;jump(Number(e.target.value));});$('timeline-slider').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?7:1;jump(e.key==='Home'?0:e.key==='End'?maxDay:target+(['ArrowLeft','PageDown'].includes(e.key)?-1:1)*(e.key.startsWith('Page')?14:step));});
$('timeline-slider').addEventListener('change',()=>{dragging=false;});
$('play').addEventListener('click',()=>{if(position>=maxDay-.001){position=target=0;}playing=!playing;uiTime=0;});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.unit){displayMode=b.dataset.unit;savePref('fasl-units',displayMode);uiTime=0;return;}if(b.dataset.scene)jump(b.dataset.scene==='rice'?0:Sim.wheatStart());if(b.dataset.drawer)openDrawer(b.dataset.drawer);if(b.dataset.residue){setResidue(b.dataset.residue);return;}if(b.id==='change-residue'){$('drawer').close();pendingSeek=position;resumeAfterChoice=false;chooseResidue();return;}if(b.id==='language'){language=language==='en'?'pa':'en';savePref('fasl-language',language);applyLabels();$('drawer').close();openDrawer('about');return;}if(b.id==='theme'){theme=theme==='system'?'light':theme==='light'?'dark':'system';savePref('fasl-theme',theme);applyTheme();$('drawer').close();openDrawer('about');return;}if(b.id==='close-drawer')$('drawer').close();if(b.id==='motion'){reduced=!reduced;if(reduced)playing=false;$('drawer').close();}if(b.id==='export'){const blob=new Blob([JSON.stringify({mode:'managed_rotation',modelVersion:2,displayMode,residueStrategy,soil:result.state.soil,seed:result.seed,scenario:result.scenario,assumptions:result.cfg,automaticPolicy:Sim.AUTO_CONFIG,decisions:result.actions,waterLedger:result.state.water,cropStates:result.state.cropStates},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fasl-automatic-rotation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
function openDrawer(kind){playing=false;const v=current||Timeline.sample(result,flows,position);let title,html;
 if(kind==='metrics'){title=tr('Live crop metrics','ਫ਼ਸਲ ਦੇ ਮੌਜੂਦਾ ਅੰਕੜੇ');html=metricsDetails(v);}
 else if(kind==='soil'){title=tr('Soil condition','ਮਿੱਟੀ ਦੀ ਹਾਲਤ');html=soilDetails(v);}
 else
 if(['fertilizer','herbicide','pest_control'].includes(kind)){title={fertilizer:'Plant food, at the right time',herbicide:'Room for roots',pest_control:'Treatment only when needed'}[kind];const rows=v.s.cropStates[v.id].products.filter(p=>p.category===kind);html='<p>'+basisLabel(v)+'.</p><p>The bottle shows the amount remaining from this season’s total scheduled applications. Moving backward restores the earlier amount. Crop care is automatic; the table lists applications scheduled through this day.</p>'+ (rows.length?'<table><tr><th>Date</th><th>Product</th><th>Applied</th></tr>'+rows.map(p=>`<tr><td>${p.date}</td><td>${esc(p.product)}</td><td>${productAmount(p,v)}</td></tr>`).join('')+'</table>':'<p>No application yet. The demonstration does not apply pesticide on a calendar schedule.</p>');}
 else{title='A year in one field';html=`<p>Slide through a continuous rice → fallow → wheat rotation, or press play. Growth, rain, irrigation, nutrition and identified pest scenarios follow an automatic baseline. At rice harvest, choose to burn straw or keep it as mulch. All other care stays automatic.</p><p>Water travels from the aquifer up the tubewell, out onto the field, through a surface pool, and into the soil. Plants draw water from the root zone; drainage returns to groundwater after the model’s seven-day lag.</p><p>Each daily water balance is spread across the timeline so rainfall and irrigation precede infiltration, plant water use and drainage. Particle travel, wind and water waves are illustrative; they do not add water to the ledger.</p><p>Rain uses IMD Ludhiana 1991–2020 monthly averages with deterministic synthetic rainy dates. Groundwater height maps a model storage bucket, not a measured water-table depth. Growth timing, water parameters and responses are illustrative.</p><button class="action" id="motion">${reduced?'Enable':'Reduce'} motion</button><button class="action" id="export">Export automatic rotation</button>${waterDetails(v)}<h3>Primary sources</h3>${DATA.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a>`).join('')}<p>Educational simulation, not agronomic instructions. Automatic product applications are historical source examples within the supplied package.</p>`;}
 if(kind==='about'){html=settingsHTML()+html;}
 if(language==='pa'&&!['soil','metrics'].includes(kind)){title=tr(title,kind==='about'?'ਇੱਕ ਖੇਤ ਦਾ ਸਾਲ':kind==='fertilizer'?'ਖਾਦ':kind==='herbicide'?'ਨਦੀਨ ਕੰਟਰੋਲ':'ਕੀਟ ਕੰਟਰੋਲ');html=kind==='about'?settingsHTML()+punjabiAbout(v)+waterDetails(v):punjabiInputs(v,kind);}
 $('drawer-title').textContent=title;$('drawer-content').innerHTML=html;$('drawer').showModal();uiTime=0;
}
function frame(time){requestAnimationFrame(frame);const dt=lastTime?Math.min(.05,(time-lastTime)/1000):0;lastTime=time;if(document.hidden)return;
 if(playing){target=Math.min(maxDay,target+dt*speed);if(!residueStrategy&&target>=121){target=121;resumeAfterChoice=true;chooseResidue();}if(target>=maxDay)playing=false;}
 position=reduced?target:Math.abs(target-position)<.0001?target:position+(target-position)*(1-Math.exp(-dt*10));
 current=Timeline.sample(result,flows,position);Scene3D.update(current,{motion:reduced,time:time/1000,dt});
 if(time-uiTime>100||uiTime===0){updateUI(current);uiTime=time;}
}


function count(n){return n>=1000000?fmt(n/1000000,2)+'M':n>=10000?fmt(n/1000,1)+'k':fmt(n,n<10?1:0);}
function mass(kg){return displayMode==='bowl'?fmt(kg*1000,1)+' g':fmt(kg,kg<10?1:0)+' kg';}
function basisLabel(v){return displayMode==='acre'?tr('1 acre','1 ਏਕੜ'):tr('Per 100 g dry '+(v.id==='rice'?'rice':'wheat grain'),'100 g ਸੁੱਕਾ '+(v.id==='rice'?'ਚੌਲ':'ਕਣਕ')+' ਪ੍ਰਤੀ ਕੌਲੀ');}
function productAmount(p,v){const m=Metrics.sample(result,v,displayMode),f=p.date===v.s.date?Timeline.phase(v.fraction,0,.3):1,n=p.quantity*f*m.scale;return p.unit==='kg'&&displayMode==='bowl'?fmt(n*1000,3)+' g':fmt(n,displayMode==='bowl'?3:2)+' '+p.unit;}
function soilAmount(n,unit,v){const scale=Metrics.sample(result,v,displayMode).scale;return displayMode==='bowl'?fmt(n*scale*1000,3)+' '+(unit==='kg N'?'g N':'g'):fmt(n,1)+' '+unit;}
function waterDetails(v){const m=Metrics.sample(result,v,displayMode);return `<h3>${tr('Water balance','ਪਾਣੀ ਦਾ ਹਿਸਾਬ')} · ${basisLabel(v)}</h3><table>${[[tr('Rain','ਮੀਂਹ'),m.water.rain],[tr('Gross pumping','ਕੁੱਲ ਪੰਪ ਕੀਤਾ'),m.water.pumped],[tr('Plant use + evaporation','ਫ਼ਸਲ ਦੀ ਖਪਤ ਅਤੇ ਭਾਫ਼'),m.water.et],[tr('Arrived recharge','ਪਹੁੰਚੀ ਭਰਪਾਈ'),m.water.recharge],[tr('Groundwater storage','ਧਰਤੀ ਹੇਠਲਾ ਪਾਣੀ'),v.aquiferL*m.scale]].map(([label,n])=>`<tr><td>${label}</td><td>${liters(n)}</td></tr>`).join('')}</table><p>${tr('Rotation totals; bowl mode allocates this acre’s totals to the active crop’s final dry output. Groundwater percentage and rainfall depth keep their original scale.','ਪੂਰੇ ਚੱਕਰ ਦੇ ਅੰਕੜੇ; ਕੌਲੀ ਮੋਡ ਵਿੱਚ ਇਸ ਏਕੜ ਦੇ ਅੰਕੜੇ ਮੌਜੂਦਾ ਫ਼ਸਲ ਦੇ ਅੰਤਿਮ ਸੁੱਕੇ ਅਨਾਜ ਦੇ ਹਿੱਸੇ ਅਨੁਸਾਰ ਹਨ। ਪਾਣੀ ਦੀ ਪ੍ਰਤੀਸ਼ਤ ਅਤੇ ਮੀਂਹ ਦੀ ਡੂੰਘਾਈ ਨਹੀਂ ਬਦਲਦੇ।')}</p>`;}
function metricsDetails(v){const m=Metrics.sample(result,v,displayMode);return `<p>${basisLabel(v)}</p><table>${[[tr('Standing plants (estimate)','ਖੜ੍ਹੇ ਪੌਦੇ (ਅੰਦਾਜ਼ਾ)'),count(m.plants)],[tr('Shoots including tillers (estimate)','ਟਾਹਣੀਆਂ ਸਮੇਤ ਫੁਟਾਰਾ (ਅੰਦਾਜ਼ਾ)'),count(m.shoots)],[tr('Water pumped · this crop','ਪੰਪ ਕੀਤਾ ਪਾਣੀ · ਇਸ ਫ਼ਸਲ ਲਈ'),liters(m.pumpedL)],[tr('Rain · this crop','ਮੀਂਹ · ਇਸ ਫ਼ਸਲ ਲਈ'),liters(m.rainL)],[tr('Plant use + evaporation','ਫ਼ਸਲ ਦੀ ਖਪਤ ਅਤੇ ਭਾਫ਼'),liters(m.etL)],[tr(m.harvested?'Harvested dry grain':'Dry grain forming (estimate)',m.harvested?'ਵਾਢੀ ਦਾ ਸੁੱਕਾ ਅਨਾਜ':'ਬਣ ਰਿਹਾ ਸੁੱਕਾ ਅਨਾਜ (ਅੰਦਾਜ਼ਾ)'),mass(m.grainKg)],[tr('Final dry output (projection)','ਅੰਤਿਮ ਸੁੱਕਾ ਅਨਾਜ (ਅੰਦਾਜ਼ਾ)'),mass(m.edibleKg*m.scale)]].map(([label,value])=>`<tr><td>${label}</td><td>${value}</td></tr>`).join('')}</table><p>${tr('One enlarged crop represents the field. Plant numbers rise with emergence, stay stable through tillering and fall as the crop is harvested. Shoots increase separately. Grain accumulation follows the illustrative grain-filling phase.','ਇੱਕ ਵੱਡਾ ਪੌਦਾ ਖੇਤ ਦੀ ਨੁਮਾਇੰਦਗੀ ਕਰਦਾ ਹੈ। ਪੌਦਿਆਂ ਦੀ ਗਿਣਤੀ ਉੱਗਣ ਨਾਲ ਵਧਦੀ ਹੈ, ਫੁਟਾਰੇ ਦੌਰਾਨ ਸਥਿਰ ਰਹਿੰਦੀ ਹੈ ਅਤੇ ਵਾਢੀ ਨਾਲ ਘਟਦੀ ਹੈ। ਟਾਹਣੀਆਂ ਵੱਖਰੇ ਤੌਰ ਉੱਤੇ ਵਧਦੀਆਂ ਹਨ। ਅਨਾਜ ਦਾ ਵਾਧਾ ਮਾਡਲ ਦੇ ਦਾਣਾ ਭਰਨ ਦੇ ਪੜਾਅ ਅਨੁਸਾਰ ਹੈ।')}</p><p>${tr('Rice target: 20 × 15 cm spacing and 2 seedlings per hill (PAU). Wheat: illustrative 250 plants/m². Emergence, shoot counts and no plant mortality are demonstration assumptions, not measured field populations.','ਝੋਨਾ: 20 × 15 cm ਦੂਰੀ ਅਤੇ ਹਰ ਥਾਂ 2 ਪਨੀਰੀ ਦੇ ਪੌਦੇ (PAU)। ਕਣਕ: ਮਾਡਲ ਲਈ 250 ਪੌਦੇ/m²। ਉੱਗਣ, ਟਾਹਣੀਆਂ ਅਤੇ ਪੌਦਿਆਂ ਦੀ ਮੌਤ ਨਾ ਹੋਣ ਦੀਆਂ ਧਾਰਨਾਵਾਂ ਖੇਤ ਦੇ ਮਾਪ ਨਹੀਂ ਹਨ।')}</p><p>${tr('A bowl means 100 g dry edible output. Its field share uses this crop’s final modeled harvest, so water and inputs remain comparable throughout scrubbing.','ਕੌਲੀ ਦਾ ਮਤਲਬ 100 g ਸੁੱਕਾ ਖਾਣ ਯੋਗ ਅਨਾਜ ਹੈ। ਖੇਤ ਦਾ ਹਿੱਸਾ ਇਸ ਫ਼ਸਲ ਦੇ ਮਾਡਲ ਦੇ ਅੰਤਿਮ ਝਾੜ ਅਨੁਸਾਰ ਹੈ।')}</p><a class="source-link" href="https://pau.edu/content/ccil/pf/pp_kharif.pdf" target="_blank" rel="noopener">${tr('PAU transplant spacing ↗','PAU ਲੁਆਈ ਦੀ ਦੂਰੀ ↗')}</a>`;}

function stageLabel(v){const labels={rice:['ਬਿਜਾਈ','ਪਨੀਰੀ','ਲੁਆਈ','ਫੁਟਾਰਾ','ਮੁੰਜਰ ਬਣਨਾ','ਗੋਭ','ਫੁੱਲ','ਦਾਣਾ ਭਰਨਾ','ਪੱਕਣਾ','ਵਾਢੀ'],wheat:['ਬਿਜਾਈ','ਉੱਗਣਾ','ਜੜ੍ਹਾਂ ਦਾ ਵਾਧਾ','ਫੁਟਾਰਾ','ਗੰਢਾਂ ਬਣਨਾ','ਗੋਭ','ਸਿੱਟੇ ਨਿਕਲਣਾ','ਦਾਣਾ ਭਰਨਾ','ਪੱਕਣਾ','ਵਾਢੀ']};return tr(v.stage.label,labels[v.id][v.def.stages.indexOf(v.stage)]||v.stage.label);}
function soilLabel(trend){return trend==='improving'?tr('↑ Improving trend','↑ ਸੁਧਾਰ ਵੱਲ'):trend==='declining'?tr('↓ Declining trend','↓ ਗਿਰਾਵਟ ਵੱਲ'):tr('↔ Baseline','↔ ਸ਼ੁਰੂਆਤੀ ਹਾਲਤ');}
function applyTheme(){document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;document.querySelector('meta[name="theme-color"]').content=document.documentElement.dataset.theme==='dark'?'#14231e':'#f3f0e5';}
function applyLabels(){document.querySelector('[data-unit=bowl]').textContent=tr('Per bowl','ਪ੍ਰਤੀ ਕੌਲੀ');document.querySelector('[data-unit=acre]').textContent=tr('1 acre','1 ਏਕੜ');document.querySelector('.unit-switch').setAttribute('aria-label',tr('Display units','ਮਾਤਰਾ ਦੀ ਇਕਾਈ'));document.querySelector('.live-metrics').setAttribute('aria-label',tr('Live crop metrics','ਫ਼ਸਲ ਦੇ ਮੌਜੂਦਾ ਅੰਕੜੇ'));document.documentElement.lang=language;document.querySelectorAll('[data-scene]').forEach(b=>b.textContent=tr(b.dataset.scene==='rice'?'Rice':'Wheat',b.dataset.scene==='rice'?'ਝੋਨਾ':'ਕਣਕ'));for(const [cat,en,pa] of [['fertilizer','Fertilizer','ਖਾਦ'],['herbicide','Weeds','ਨਦੀਨ'],['pest_control','Pests','ਕੀਟ']]){const b=document.querySelector('[data-drawer="'+cat+'"]');b.querySelector('small').textContent=tr(en,pa);b.setAttribute('aria-label',tr(en,pa));}document.querySelector('.menu').textContent=tr('Menu','ਮੀਨੂ');document.querySelector('.menu').setAttribute('aria-label',tr('Settings and information','ਸੈਟਿੰਗਾਂ ਅਤੇ ਜਾਣਕਾਰੀ'));document.querySelector('.timeline-speed').textContent=tr('Auto care','ਆਪਣੇ ਆਪ ਦੇਖਭਾਲ');$('timeline-slider').setAttribute('aria-label',tr('Crop growing timeline','ਫ਼ਸਲ ਦੀ ਸਮਾਂ ਰੇਖਾ'));$('close-drawer').setAttribute('aria-label',tr('Close details','ਵੇਰਵੇ ਬੰਦ ਕਰੋ'));document.querySelector('.drawer-top>span').textContent=tr('FIELD NOTES','ਖੇਤ ਦੇ ਵੇਰਵੇ');document.querySelector('.timeline-endpoints').innerHTML='<span>'+tr('Jun · Rice','ਜੂਨ · ਝੋਨਾ')+'</span><span>'+tr('Oct → Nov · Wheat','ਅਕਤੂਬਰ → ਨਵੰਬਰ · ਕਣਕ')+'</span><span>'+tr('Apr · Harvest','ਅਪ੍ਰੈਲ · ਵਾਢੀ')+'</span>';document.querySelectorAll('[data-month]').forEach(el=>el.textContent=language==='pa'?paMonths[Number(el.dataset.month.slice(5))-1]:new Date(el.dataset.month+'-01T00:00:00Z').toLocaleDateString('en',{month:'short',timeZone:'UTC'}));uiTime=0;}
function chooseResidue(){playing=false;$('residue-title').textContent=tr('Rice harvested. What happens to the straw?','ਝੋਨੇ ਦੀ ਵਾਢੀ ਹੋ ਗਈ। ਪਰਾਲੀ ਦਾ ਕੀ ਕਰਨਾ ਹੈ?');$('residue-description').textContent=tr('Choose one path. Watch its effect through the wheat season.','ਇੱਕ ਰਾਹ ਚੁਣੋ। ਕਣਕ ਦੇ ਮੌਸਮ ਵਿੱਚ ਇਸ ਦਾ ਅਸਰ ਦੇਖੋ।');document.querySelector('[data-residue="mulch"]').textContent=tr('Keep as mulch · Chop, spread & sow wheat','ਮਲਚ ਵਜੋਂ ਰੱਖੋ · ਕੁਤਰਾ ਕਰੋ, ਵਿਛਾਓ ਅਤੇ ਕਣਕ ਬੀਜੋ');document.querySelector('[data-residue="burn"]').textContent=tr('Burn straw · Fire, smoke & ash','ਪਰਾਲੀ ਸਾੜੋ · ਅੱਗ, ਧੂੰਆਂ ਅਤੇ ਸੁਆਹ');if(!$('residue-dialog').open)$('residue-dialog').showModal();}
$('residue-dialog').addEventListener('cancel',e=>{e.preventDefault();$('residue-dialog').close();pendingSeek=null;resumeAfterChoice=false;});
function setResidue(strategy){residueStrategy=strategy;result=Sim.ideal({residueStrategy:strategy});flows=Timeline.prepare(result);for(const id of ['rice','wheat'])for(const cat of Object.keys(planned[id]))planned[id][cat]=result.state.cropStates[id].products.filter(p=>p.category===cat).reduce((n,p)=>n+p.quantity,0);$('residue-dialog').close();target=pendingSeek??Math.max(121,target);pendingSeek=null;playing=resumeAfterChoice;uiTime=0;}
function settingsHTML(){return `<div class="settings"><button class="action" id="language">${tr('Language: English → ਪੰਜਾਬੀ','ਭਾਸ਼ਾ: ਪੰਜਾਬੀ → English')}</button><button class="action" id="theme">${tr('Theme','ਦਿੱਖ')}: ${tr(theme,{system:'ਸਿਸਟਮ',light:'ਹਲਕੀ',dark:'ਗੂੜ੍ਹੀ'}[theme])}</button>${residueStrategy?`<button class="action" id="change-residue">${tr('Change residue method','ਪਰਾਲੀ ਦਾ ਤਰੀਕਾ ਬਦਲੋ')}</button>`:''}</div>`;}
function soilDetails(v){return `<p class="soil-trend">${soilLabel(v.soil.trend)}</p><p>${tr(v.soil.trend==='baseline'?'Starting condition. No soil test has been supplied.':v.soil.trend==='improving'?'Retained straw covers the soil and gradually returns nutrients. Soil-carbon benefits develop over repeated seasons.':'Burning removes organic inputs and loses residue nutrients. Ash remains; this does not imply instant crop failure.',v.soil.trend==='baseline'?'ਸ਼ੁਰੂਆਤੀ ਹਾਲਤ। ਮਿੱਟੀ ਦੀ ਜਾਂਚ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।':v.soil.trend==='improving'?'ਪਰਾਲੀ ਮਿੱਟੀ ਨੂੰ ਢੱਕਦੀ ਹੈ ਅਤੇ ਹੌਲੀ-ਹੌਲੀ ਪੌਸ਼ਟਿਕ ਤੱਤ ਵਾਪਸ ਕਰਦੀ ਹੈ। ਕਾਰਬਨ ਦੇ ਲਾਭ ਕਈ ਮੌਸਮਾਂ ਵਿੱਚ ਬਣਦੇ ਹਨ।':'ਸਾੜਨ ਨਾਲ ਜੈਵਿਕ ਪਦਾਰਥ ਅਤੇ ਪੌਸ਼ਟਿਕ ਤੱਤ ਘਟਦੇ ਹਨ। ਸੁਆਹ ਰਹਿੰਦੀ ਹੈ; ਇਸ ਦਾ ਮਤਲਬ ਤੁਰੰਤ ਫ਼ਸਲ ਖਰਾਬ ਹੋਣਾ ਨਹੀਂ ਹੈ।')}</p><h3>${tr('Nutrition','ਪੋਸ਼ਣ')} · ${basisLabel(v)}</h3><table>${[[tr('Fertilizer nitrogen applied','ਖਾਦ ਤੋਂ ਦਿੱਤਾ ਨਾਈਟ੍ਰੋਜਨ'),v.soil.fertilizerN,'kg N'],[tr('Straw remaining','ਬਾਕੀ ਪਰਾਲੀ'),v.soil.residueKg,'kg'],[tr('Residue nitrogen returned (modeled)','ਪਰਾਲੀ ਤੋਂ ਵਾਪਸ ਨਾਈਟ੍ਰੋਜਨ (ਮਾਡਲ)'),v.soil.residueNReturned,'kg N'],[tr('Residue nitrogen lost (modeled)','ਪਰਾਲੀ ਤੋਂ ਨਾਈਟ੍ਰੋਜਨ ਦਾ ਨੁਕਸਾਨ (ਮਾਡਲ)'),v.soil.residueNRemoved,'kg N']].map(([label,n,unit])=>`<tr><td>${label}</td><td>${soilAmount(n,unit,v)}</td></tr>`).join('')}</table><p>${tr('Applied nitrogen is not available soil nitrogen. Fertilizer supports crop nutrition; it does not automatically improve soil health.','ਦਿੱਤਾ ਨਾਈਟ੍ਰੋਜਨ ਮਿੱਟੀ ਵਿੱਚ ਉਪਲਬਧ ਨਾਈਟ੍ਰੋਜਨ ਦੇ ਬਰਾਬਰ ਨਹੀਂ ਹੈ। ਖਾਦ ਫ਼ਸਲ ਨੂੰ ਪੋਸ਼ਣ ਦਿੰਦੀ ਹੈ; ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਆਪਣੇ ਆਪ ਨਹੀਂ ਸੁਧਰਦੀ।')}</p><h3>${tr('Research evidence','ਖੋਜ ਦੇ ਸਬੂਤ')}</h3><p>${tr('A north-west India study reported surface soil organic carbon of 5.15 g/kg under Happy Seeder residue retention versus 4.61 g/kg under conventional tillage: a difference of 0.54 g/kg (11.7%). These are study observations, not predictions for this field or a burn comparison.','ਉੱਤਰ-ਪੱਛਮੀ ਭਾਰਤ ਦੇ ਅਧਿਐਨ ਵਿੱਚ ਹੈਪੀ ਸੀਡਰ ਨਾਲ ਪਰਾਲੀ ਰੱਖਣ ਹੇਠ ਕਾਰਬਨ 5.15 g/kg ਅਤੇ ਰਵਾਇਤੀ ਵਾਹੀ ਹੇਠ 4.61 g/kg ਸੀ: ਫ਼ਰਕ 0.54 g/kg (11.7%)। ਇਹ ਖੋਜ ਦੇ ਅੰਕੜੇ ਹਨ, ਇਸ ਖੇਤ ਦੀ ਭਵਿੱਖਬਾਣੀ ਜਾਂ ਸਾੜਨ ਨਾਲ ਤੁਲਨਾ ਨਹੀਂ।')}</p><a class="source-link" href="https://epubs.icar.org.in/index.php/JSWC/article/view/165436" target="_blank" rel="noopener">${tr('Read soil study ↗','ਮਿੱਟੀ ਦਾ ਅਧਿਐਨ ਪੜ੍ਹੋ ↗')}</a><p>${tr('Demonstration assumptions: 3,000 kg straw/acre, 0.6% straw N, 90% N loss when burned, 180-day exponential decomposition, and an initial 12% reduction in combined soil/plant water loss under mulch. Released residue N is informational, not credited as immediately plant-available. Yield has no fixed burn penalty.','ਮਾਡਲ ਦੀਆਂ ਧਾਰਨਾਵਾਂ: 3,000 kg ਪਰਾਲੀ/ਏਕੜ, 0.6% ਨਾਈਟ੍ਰੋਜਨ, ਸਾੜਨ ਨਾਲ 90% ਨਾਈਟ੍ਰੋਜਨ ਨੁਕਸਾਨ, 180 ਦਿਨਾਂ ਦੇ ਅਨੁਪਾਤ ਨਾਲ ਸੜਨਾ, ਮਲਚ ਹੇਠ ਸ਼ੁਰੂ ਵਿੱਚ 12% ਘੱਟ ਪਾਣੀ ਦੀ ਖਪਤ। ਪਰਾਲੀ ਦਾ ਨਾਈਟ੍ਰੋਜਨ ਤੁਰੰਤ ਫ਼ਸਲ ਨੂੰ ਉਪਲਬਧ ਨਹੀਂ ਮੰਨਿਆ ਗਿਆ। ਸਾੜਨ ਲਈ ਝਾੜ ਦੀ ਕੋਈ ਨਿਸ਼ਚਿਤ ਕਟੌਤੀ ਨਹੀਂ।')}</p>${residueStrategy?'<button class="action" id="change-residue">'+tr('Change residue method','ਪਰਾਲੀ ਦਾ ਤਰੀਕਾ ਬਦਲੋ')+'</button>':''}`;}
function punjabiInputs(v,kind){const rows=v.s.cropStates[v.id].products.filter(p=>p.category===kind);return '<p>'+basisLabel(v)+'</p><p>ਬੋਤਲ ਇਸ ਮੌਸਮ ਦੀ ਬਾਕੀ ਮਾਤਰਾ ਦਿਖਾਉਂਦੀ ਹੈ। ਸਮਾਂ ਪਿੱਛੇ ਕਰਨ ਨਾਲ ਮਾਤਰਾ ਵਾਪਸ ਆਉਂਦੀ ਹੈ। ਦੇਖਭਾਲ ਆਪਣੇ ਆਪ ਹੁੰਦੀ ਹੈ।</p><table><tr><th>ਤਾਰੀਖ਼</th><th>ਉਤਪਾਦ</th><th>ਮਾਤਰਾ</th></tr>'+rows.map(p=>`<tr><td>${p.date}</td><td>${esc(p.product)}</td><td>${productAmount(p,v)}</td></tr>`).join('')+'</table>'+(rows.length?'':'<p>ਅਜੇ ਕੋਈ ਵਰਤੋਂ ਨਹੀਂ ਹੋਈ।</p>');}
function punjabiAbout(v){return '<p>ਝੋਨਾ → ਖਾਲੀ ਖੇਤ → ਕਣਕ। ਸਮਾਂ ਰੇਖਾ ਖਿਸਕਾਓ ਜਾਂ ਚਲਾਓ। ਵਾਢੀ ਵੇਲੇ ਪਰਾਲੀ ਦਾ ਤਰੀਕਾ ਚੁਣੋ। ਬਾਕੀ ਦੇਖਭਾਲ ਆਪਣੇ ਆਪ ਹੁੰਦੀ ਹੈ।</p><p>ਪਾਣੀ ਟਿਊਬਵੈੱਲ ਤੋਂ ਖੇਤ ਵਿੱਚ ਆਉਂਦਾ ਹੈ, ਇਕੱਠਾ ਹੁੰਦਾ ਹੈ ਅਤੇ ਮਿੱਟੀ ਵਿੱਚ ਰਿਸਦਾ ਹੈ। ਭਰਪਾਈ ਮਾਡਲ ਵਿੱਚ ਸੱਤ ਦਿਨ ਬਾਅਦ ਹੁੰਦੀ ਹੈ। ਮੀਂਹ IMD ਲੁਧਿਆਣਾ ਦੇ ਔਸਤ ਅੰਕੜਿਆਂ ਉੱਤੇ ਆਧਾਰਿਤ ਹੈ। ਧਰਤੀ ਹੇਠਲੇ ਪਾਣੀ ਦੀ ਉਚਾਈ ਅਸਲ ਮਾਪ ਨਹੀਂ ਹੈ।</p><button class="action" id="motion">'+(reduced?'ਹਰਕਤ ਚਾਲੂ ਕਰੋ':'ਹਰਕਤ ਘਟਾਓ')+'</button><button class="action" id="export">ਸਿਮੂਲੇਸ਼ਨ ਡਾਊਨਲੋਡ ਕਰੋ</button><h3>ਸਰੋਤ</h3>'+DATA.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a>`).join('')+'<p>ਸਿੱਖਿਆ ਲਈ ਸਿਮੂਲੇਸ਼ਨ। ਖੇਤੀ ਦੀ ਸਲਾਹ ਨਹੀਂ।</p>';}
applyTheme();applyLabels();matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(theme==='system')applyTheme();});

requestAnimationFrame(frame);
window.Fieldnotes={Sim,Timeline,Metrics,Scene3D,getResult:()=>result,getTimeline:()=>({position,target,playing,mode:'managed_rotation',residueStrategy,displayMode,metrics:current?Metrics.sample(result,current,displayMode):null,sample:current}),planned};
