'use strict';
const $=id=>document.getElementById(id),fmt=(n,d=1)=>Number(n).toLocaleString('en',{maximumFractionDigits:d}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const result=Sim.ideal(),flows=Timeline.prepare(result),maxDay=result.snapshots.length;
let position=0,target=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,lastTime=0,uiTime=0,current,dragging=false;
const speed=1.5;
// No old decision-game save is loaded or overwritten by this automatic demonstration.
const planned={};for(const id of ['rice','wheat']){const crop=result.state.cropStates[id];planned[id]={};for(const cat of ['fertilizer','herbicide','pest_control'])planned[id][cat]=crop.products.filter(p=>p.category===cat).reduce((n,p)=>n+p.quantity,0);}
function bottle(key,label,color){return `<svg viewBox="0 0 48 68" aria-hidden="true"><defs><clipPath id="clip-${key}"><path d="M14 16h20l5 8v36q-15 6-30 0V24z"/></clipPath></defs><path d="M14 8h20v9l5 7v36q-15 6-30 0V24l5-7z" fill="#e8e6d1" fill-opacity=".65" stroke="#9aaa89"/><g clip-path="url(#clip-${key})"><rect class="bottle-liquid" x="8" y="17" width="32" height="47" fill="${color}" opacity=".8"/></g><path d="M15 7h19v7H15z" fill="#637953"/><path d="M13 29h23v21H13z" fill="#f3f0dd" opacity=".85"/><text x="24" y="43" text-anchor="middle" font-family="Georgia" font-size="14" fill="#657856">${label}</text><path d="M12 25v29" stroke="#fff" opacity=".65"/></svg>`;}
for(const [id,label,color] of [['fert','N','#a8ad67'],['weed','W','#8ea67f'],['pest','P','#c5b58c']])$(id+'-icon').innerHTML=bottle(id,label,color);
const monthMarks=[];const first=new Date(Sim.dateAt(0)+'T00:00:00Z');let month=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,1));monthMarks.push({day:0,label:'Jun',key:'2027-06'});while(month<=new Date(Sim.dateAt(maxDay)+'T00:00:00Z')){const day=(month-first)/Sim.MS;monthMarks.push({day,label:month.toLocaleDateString('en',{month:'short',timeZone:'UTC'}),key:month.toISOString().slice(0,7)});month=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,1));}
$('timeline-slider').max=maxDay;$('month-list').innerHTML=monthMarks.map(m=>`<span style="left:${m.day/maxDay*100}%" data-month="${m.key}">${m.label}</span>`).join('');$('timeline-ticks').innerHTML=monthMarks.map(m=>`<i style="left:${m.day/maxDay*100}%"></i>`).join('');
function liters(n){return n>=1e6?fmt(n/1e6,2)+'M L':n>=1000?fmt(n/1000,1)+'k L':fmt(n,0)+' L';}
function updateUI(v){
 const date=new Date(Sim.dateAt(v.day)+'T00:00:00Z'),stage=v.fallow?'Fallow · the soil rests':v.stage.label;
 $('stage-title').textContent=stage;$('current-date').textContent=date.toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
 $('timeline-caption').textContent=(v.fallow?'Between seasons':v.def.name)+' · '+date.toLocaleDateString('en',{day:'numeric',month:'short',timeZone:'UTC'});
 $('timeline-slider').value=target;$('timeline-slider').style.setProperty('--progress',position/maxDay*100+'%');$('timeline-slider').setAttribute('aria-valuetext',`${date.toLocaleDateString('en',{day:'numeric',month:'long',timeZone:'UTC'})}, ${stage}`);
 document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scene===v.id&&!v.fallow));document.querySelectorAll('[data-month]').forEach(m=>m.classList.toggle('current-month',m.dataset.month===Sim.dateAt(v.day).slice(0,7)));
 $('play').textContent=playing?'Ⅱ':'▷';$('play').setAttribute('aria-label',playing?'Pause simulation':'Play simulation');
 $('pump-used').textContent=liters(v.water.pumped)+' pumped';const effects=Scene3D.info();document.querySelector('.pump-state').classList.toggle('running',effects.pumpStrength>.05);
 $('weather-status').textContent=effects.rainStrength>.1&&v.flow.rain>0?'Rain · '+fmt(v.s.rainMm,1)+' mm':effects.pumpStrength>.1?'Tubewell watering':effects.infiltrationAnimating?'Water seeping into soil':v.flow.recharge>0?'Groundwater recharging':v.flow.queuedRecharge>0&&v.fraction>.8?'Drainage toward groundwater':v.fallow?'The soil rests':'A breeze through the field';
 for(const [id,cat] of [['fert','fertilizer'],['weed','herbicide'],['pest','pest_control']]){const capacity=planned[v.id][cat],remaining=capacity?Math.max(0,1-v.totals[cat]/capacity):1,liquid=$(id+'-icon').querySelector('.bottle-liquid');liquid.setAttribute('height',47*remaining);liquid.setAttribute('y',64-47*remaining);$(id+'-icon').dataset.remaining=remaining;$(id+'-icon').closest('button').title=capacity?fmt(remaining*100,0)+'% of this season’s planned inputs remaining':'No treatment needed this season';}
 const prev=v.previous.aquifer,diff=v.aquiferL-prev;$('groundwater-label').textContent=(Math.abs(diff)<.5?'↔':diff>0?'↑':'↓')+' Groundwater · '+fmt(v.aquiferL/Sim.H.aquifer_capacity_L*100,1)+'%';
}
function jump(value){playing=false;target=Math.max(0,Math.min(maxDay,value));if(reduced)position=target;uiTime=0;}
$('timeline-slider').addEventListener('input',e=>{dragging=true;jump(Number(e.target.value));});$('timeline-slider').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?7:1;jump(e.key==='Home'?0:e.key==='End'?maxDay:target+(['ArrowLeft','PageDown'].includes(e.key)?-1:1)*(e.key.startsWith('Page')?14:step));});
$('timeline-slider').addEventListener('change',()=>{dragging=false;});
$('play').addEventListener('click',()=>{if(position>=maxDay-.001){position=target=0;}playing=!playing;uiTime=0;});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.scene)jump(b.dataset.scene==='rice'?0:Sim.wheatStart());if(b.dataset.drawer)openDrawer(b.dataset.drawer);if(b.id==='close-drawer')$('drawer').close();if(b.id==='motion'){reduced=!reduced;if(reduced)playing=false;$('drawer').close();}if(b.id==='export'){const blob=new Blob([JSON.stringify({mode:'automatic_baseline',seed:result.seed,scenario:result.scenario,assumptions:Sim.CONFIG,automaticPolicy:Sim.AUTO_CONFIG,decisions:result.actions,waterLedger:result.state.water,cropStates:result.state.cropStates},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fasl-automatic-rotation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
function openDrawer(kind){playing=false;const v=current;let title,html;
 if(['fertilizer','herbicide','pest_control'].includes(kind)){title={fertilizer:'Plant food, at the right time',herbicide:'Room for roots',pest_control:'Treatment only when needed'}[kind];const rows=v.s.cropStates[v.id].products.filter(p=>p.category===kind);html='<p>The bottle shows the amount remaining from this season’s total scheduled applications. Moving backward restores the earlier amount. Crop care is automatic; the table lists applications scheduled through this day.</p>'+ (rows.length?'<table><tr><th>Date</th><th>Product</th><th>Applied</th></tr>'+rows.map(p=>`<tr><td>${p.date}</td><td>${esc(p.product)}</td><td>${fmt(p.quantity,3)} ${p.unit}</td></tr>`).join('')+'</table>':'<p>No application yet. The demonstration does not apply pesticide on a calendar schedule.</p>');}
 else{title='A year in one field';html=`<p>Slide through a continuous rice → fallow → wheat rotation, or press play. Growth, rain, irrigation, nutrition and identified pest scenarios follow an automatic baseline. There are no decisions to make.</p><p>Water travels from the aquifer up the tubewell, out onto the field, through a surface pool, and into the soil. Plants draw water from the root zone; drainage returns to groundwater after the model’s seven-day lag.</p><p>Each daily water balance is spread across the timeline so rainfall and irrigation precede infiltration, plant water use and drainage. Particle travel, wind and water waves are illustrative; they do not add water to the ledger.</p><p>Rain uses IMD Ludhiana 1991–2020 monthly averages with deterministic synthetic rainy dates. Groundwater height maps a model storage bucket, not a measured water-table depth. Growth timing, water parameters and responses are illustrative.</p><button class="action" id="motion">${reduced?'Enable':'Reduce'} motion</button><button class="action" id="export">Export automatic rotation</button><h3>Water balance · this acre</h3><table>${[['Rain',v.rotationWater.rain],['Gross pumping',v.rotationWater.pumped],['Plant use + evaporation',v.rotationWater.et],['Arrived recharge',v.rotationWater.recharge],['Groundwater storage',v.aquiferL]].map(([name,n])=>`<tr><td>${name}</td><td>${fmt(n,0)} L</td></tr>`).join('')}</table><h3>Primary sources</h3>${DATA.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a>`).join('')}<p>Educational simulation, not agronomic instructions. Automatic product applications are historical source examples within the supplied package.</p>`;}
 $('drawer-title').textContent=title;$('drawer-content').innerHTML=html;$('drawer').showModal();uiTime=0;
}
function frame(time){requestAnimationFrame(frame);const dt=lastTime?Math.min(.05,(time-lastTime)/1000):0;lastTime=time;if(document.hidden)return;
 if(playing){target=Math.min(maxDay,target+dt*speed);if(target>=maxDay)playing=false;}
 position=reduced?target:Math.abs(target-position)<.0001?target:position+(target-position)*(1-Math.exp(-dt*10));
 current=Timeline.sample(result,flows,position);Scene3D.update(current,{motion:reduced,time:time/1000,dt});
 if(time-uiTime>100||uiTime===0){updateUI(current);uiTime=time;}
}
requestAnimationFrame(frame);
window.Fieldnotes={Sim,Timeline,Scene3D,getResult:()=>result,getTimeline:()=>({position,target,playing,mode:'automatic_baseline',sample:current}),planned};
