async (page) => {
  const report=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const ok=(condition,message)=>{if(!condition)throw Error(message);report.push(message);};
  const run=()=>page.evaluate(()=>window.Fieldnotes.getRun());
  const game=()=>page.evaluate(()=>({run:window.Fieldnotes.getRun(),state:window.Fieldnotes.getResult().state}));
  await page.goto('http://127.0.0.1:8080/');
  await page.setViewportSize({width:390,height:844});
  const fixture=await page.evaluate(()=>{const r={seed:126826,scenario:'normal',day:0,actions:{},runId:'acceptance-original',branchParent:null,activeScene:'rice',displayMode:'bowl'},s=Fieldnotes.Sim.simulate(r).state;return{schemaVersion:'1.0',datasetVersion:'package-1.0',randomSeed:r.seed,scenario:r.scenario,horizon:r.day,decisions:r.actions,runId:r.runId,assumptions:Fieldnotes.Sim.CONFIG};});
  await page.getByRole('button',{name:'Open game menu',exact:true}).click();
  await page.locator('#import-file').setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});
  await page.waitForFunction(()=>window.Fieldnotes.getRun().runId==='acceptance-original'&&window.Fieldnotes.getRun().day===0);
  ok((await run()).runId==='acceptance-original','File import recomputes a valid fixture');
  const initial=JSON.stringify((await game()).state);
  await page.getByRole('button',{name:'1 acre',exact:true}).click();
  await page.getByRole('button',{name:'Per bowl',exact:true}).click();
  await page.getByRole('button',{name:'Wheat ਕਣਕ',exact:true}).click();
  await page.getByRole('button',{name:'Stage 7: Heading and flowering',exact:true}).click();
  ok(JSON.stringify((await game()).state)===initial,'Unit, scene and future-stage navigation leave the ledger unchanged');
  ok(await page.locator('#view-badge').textContent()==='ARTWORK PREVIEW','Future stage visibly marked as artwork preview');
  await page.screenshot({path:'output/playwright/phone-wheat.png'});
  await page.getByRole('button',{name:'Return to live',exact:true}).click();
  const firstInfo=await page.evaluate(()=>window.Fieldnotes.Scene3D.info());
  ok(firstInfo.renderer&&firstInfo.locked&&firstInfo.revision==='182','Three.js r182 renders a locked single-crop scene');
  let lastIrrigated=-1,steps=0;
  while((await run()).day<303){
    if(++steps>330)throw Error('Rotation did not finish in 330 interactions');
    const g=await game(),s=g.state,c=s.cropStates[s.cropId],pending=s.checkpoints.find(cp=>!cp.resolved);
    if(pending){const value=pending.key==='establish'?'sow':pending.key==='transplant'?'transplant':pending.key==='weed'?'manual':pending.key==='pest'?'monitor':pending.key==='water'?'50':'full';await page.locator(`[data-choice="${value}"][data-key="${pending.key}"]`).click();continue;}
    await page.locator('#continue').click();
  }
  const complete=await game();
  ok(complete.state.cropStates.rice.harvested&&complete.state.cropStates.wheat.harvested,'Playable UI completes both crops and chronological fallow');
  ok(complete.state.maxBalanceError<1e-7,'Browser rotation retains water conservation');
  ok(complete.state.cropStates.rice.products.filter(p=>p.category==='pest_control').length===0&&complete.state.cropStates.wheat.products.filter(p=>p.category==='pest_control').length===0,'Both seasons can finish without pesticide use');
  ok(complete.state.events.some(e=>e.type==='pumping'&&e.automatic),'Automatic pumping operates through the complete rotation');
  const before=JSON.stringify(complete.state),saved=await page.evaluate(()=>window.Fieldnotes.exportRun());
  await page.reload();ok(JSON.stringify((await game()).state)===before,'Reload restores the full run from local storage');
  await page.getByRole('button',{name:'Open game menu',exact:true}).click();
  const downloaded=page.waitForEvent('download');await page.locator('#export-game').click();const file=await downloaded;ok(file.suggestedFilename().endsWith('.json'),'Export creates a downloadable game JSON');
  await page.locator('#import-file').setInputFiles({name:'exported.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await page.waitForFunction(()=>!document.querySelector('#drawer').open);
  ok(JSON.stringify((await game()).state)===before,'Export/import reconstructs identical derived stocks and events');
  await page.getByRole('button',{name:'Open game menu',exact:true}).click();
  await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,randomSeed:-3}))});
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Import rejected'));
  ok(await page.locator('#status').textContent().then(t=>t.includes('Import rejected')),'Malformed imported units are rejected with a readable message');
  ok((await run()).runId===saved.runId,'Rejected import leaves the current run intact');
  await page.locator('[data-drawer="decisions"]').click();
  await page.locator('#drawer details').filter({has:page.locator('summary',{hasText:'2027-07-12'})}).locator('summary').click();
  await page.locator('[data-replay-date="34"]').click();
  ok(await page.locator('#view-badge').textContent()==='PAST SNAPSHOT','Dated decisions expose replayable historical snapshots');
  await page.locator('[data-revise="fert34"]').selectOption('skip');
  const branched=await game();ok(branched.run.branchParent===saved.runId&&branched.run.day===303,'Editing a past choice creates a branch with its horizon preserved');
  ok(branched.state.cropStates.rice.actualYieldKg<complete.state.cropStates.rice.actualYieldKg,'A missed historical nutrient deadline changes the downstream harvest');
  await page.getByRole('button',{name:'Return to live',exact:true}).click();
  await page.getByRole('button',{name:'Rice ਝੋਨਾ',exact:true}).click();
  await page.getByRole('button',{name:'Stage 9: Dough and ripening',exact:true}).click();
  await page.screenshot({path:'output/playwright/phone-rice.png'});
  let layout=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,height:innerHeight,documentHeight:document.documentElement.scrollHeight,panelBottom:document.querySelector('.control-panel').getBoundingClientRect().bottom,canvasBottom:document.querySelector('canvas').getBoundingClientRect().bottom,panelTop:document.querySelector('.control-panel').getBoundingClientRect().top}));
  ok(layout.documentWidth===390&&layout.documentHeight===844&&layout.panelBottom<=844&&layout.canvasBottom===844,'390px phone: full viewport, no document scroll, full-screen lateral canvas beneath overlays');
  await page.getByRole('button',{name:'Open game menu',exact:true}).click();await page.locator('[data-drawer="evidence"]').click();
  ok(await page.locator('#drawer-content').textContent().then(t=>t.includes('791.1')&&t.includes('791.3')&&t.includes('Game assumptions')),'Sources sheet retains rainfall rounding discrepancy and assumption labels');
  await page.locator('#close-drawer').click();
  await page.locator('[data-stage="4"]').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');
  ok(await page.locator('#stage-title').textContent()==='Booting','Keyboard stage navigation activates the selected stage');
  await page.getByRole('button',{name:'Open game menu',exact:true}).click();await page.locator('#toggle-motion').click();await page.locator('#close-drawer').click();
  ok(JSON.stringify((await game()).state)===JSON.stringify(branched.state),'Reduced motion changes presentation without changing accounting');
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-stage="8"]').click();
  await page.screenshot({path:'output/playwright/desktop-lateral.png'});
  ok(await page.evaluate(()=>document.documentElement.scrollWidth===1440&&document.documentElement.scrollHeight===1000),'1440px desktop: full viewport without document scroll');
  ok(errors.length===0,'No browser JavaScript errors during the complete acceptance flow');
  return {passed:report.length,steps,checks:report,renderer:await page.evaluate(()=>window.Fieldnotes.Scene3D.info()),riceKg:complete.state.cropStates.rice.edibleKg,wheatKg:complete.state.cropStates.wheat.edibleKg,maxDailyErrorL:complete.state.maxBalanceError};
}
